### ISSUE TITLE
Pause button media key functionality

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#105]
**Describe the bug**
When using media keys (e.g. a pause button on a keyboard), the music doesn't pause

**To Reproduce**
1. Press the pause button on your keyboad

**Expected behavior**
Music should pause.

**Actual behavior**
Music doesn't pause and media panel shows the pause icon, then quickly switches to the play icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/71931404/217679250-df444413-9f58-4a5c-afa7-b661f3746d4c.png)
![image](https://user-images.githubusercontent.com/71931404/217679300-caf52e66-8bcc-4046-8013-7bff2d29eb7a.png)

**Log File**
[logs.txt](https://github.com/Sandakan/Oto-Music-for-Desktop/files/10691072/logs.txt)

**System Information:**
 - OS: Windows 10
 - Affected App Version: =<0.8.1-alpha

**Comment by Sandakan** [comment]
I fixed this bug in a separate branch and you won't be seeing this bug in the upcoming release.
