### ISSUE TITLE
Scroll-able volume rocker

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#106]
**Is your feature request related to a problem? Please describe.**
I always need to drag the volume bar, which takes time and is imprecise if I want to be fast (loud song, etc.)
![image](https://user-images.githubusercontent.com/71931404/217679778-3fbf0442-361c-4f26-b8fa-a12ce2d17284.png)

**Describe the solution you'd like**
It would be great if that music bar would be scroll-able.
Scrolling up is volume up, scrolling down is volume down.
This should only work when hovering over the volume rocker (the current "hit-box").

**Additional context**
Something handy would also be that you'd be able to set (in the settings) how big the interval is of each scroll.

**Comment by Sandakan** [comment]
That is a great idea.
I also found it annoying to always drag the slider whenever I wanted to change the volume of the app.
I recently added a keyboard shortcut to overcome this issue and this option will also help.
I will also be adding this feature in a future release.

**Comment by JustCallMeQuincy** [comment]
Confirmed
