### ISSUE TITLE
Using local lyrics

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#107]
**Is your feature request related to a problem? Please describe.**
I've noticed that the app always looks for lyrics online, though most of my songs have their (better) lyrics in the metadata.

**Describe the solution you'd like**
It would be handy to be able to select whether to use online- or offline lyrics.
I really like the approach the Android app has, to have the ability to fetch those lyrics if you don't have any local lyrics.

![image](https://user-images.githubusercontent.com/71931404/217680680-8a340b35-5330-41ed-990f-ef0ddcb8846f.png)

**Comment by Sandakan** [comment]
I actually fixed this problem in a separate branch and I will merge it into the master in the future.
