### ISSUE TITLE
Automatic startup doesn't work

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#108]
**Describe the bug**
Auto launch on system startup doesn't work.

**Expected behavior**
App launch on startup.

App doesn't launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/71931404/217681119-7ee334e6-309f-4bc1-b77d-135c94aeda62.png)

**System Information:**
 - OS: Windows 10
 - Affected App Version: =<0.8.1-alpha

**Comment by Sandakan** [comment]
Thanks for the heads up.
The problem is with the package I use for this process.
I found an election API that does the same thing and will add it in the next release of the app.
