### ISSUE TITLE
Minimize/close to tray

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#109]
**Is your feature request related to a problem? Please describe.**
I would love to have the option to be able to turn on my music and to then have the app sit in the background.
Minimized on the taskbar isn't very "background" to me, since I can still ALT+TAB to it etc.

**Describe the solution you'd like**
In the settings there would be a setting to minimize to tray or to close to tray.
Clicking on the tray icon could open media controls, then double-clicking would open the window.

![image](https://user-images.githubusercontent.com/71931404/217681589-7fe463db-ba28-4d36-84c0-910860b4d6ac.png)
![image](https://user-images.githubusercontent.com/71931404/217681881-c3eb104a-579f-4fa1-ae58-13131e3b3d42.png)

**Comment by Sandakan** [comment]
Thanks for the idea. I think it can be a helpful feature. I'll implement it in the app in a newer update.

**Comment by Sandakan** [comment]
Isn't it odd to add media controls to the context menu from a system tray icon?

**Comment by JustCallMeQuincy** [comment]
I suppose, though I can see it coming in handy for people who don't have media keys to control their music.
That one's up to you, you could leave it out until more people ask for it.
Not a _must_ for me.

**Comment by Sandakan** [comment]
I added the close-to-tray feature but I have to think about adding media controls to the tray icon as it requires some additional coding.
