### ISSUE TITLE
Song repetition overrides skipping

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#110]
**Describe the bug**
When skipping a song that is on "single"-repeat, it plays the song again.

**To Reproduce**
1. Play song
2. Set to repeat the song
![image](https://user-images.githubusercontent.com/71931404/218341201-4786fdbe-29d7-4eb8-82fc-8bcf6804e232.png)
3. Skip to the next (or previous) song

**Expected behavior**
The next (or previous) song should play.

**System Information:**
 - OS: Windows 10
 - Affected App Version: =<0.8.1-alpha

**Comment by Sandakan** [comment]
Oh my bad.
I thought it should repeat the same song even if you try to skip that song.
