### ISSUE TITLE
Editing songs outside of library

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#111]
**Describe the bug**
When trying to edit a song that is outside of your library, the window comes up blank.

**To Reproduce**
1. Open song outside of library
2. Right-click the title, click on "Edit song tags"
![image](https://user-images.githubusercontent.com/71931404/218533565-0e58575c-db59-40fb-88d7-b859a9049919.png)
![image](https://user-images.githubusercontent.com/71931404/218533455-e87f212e-fdf0-4267-a285-7c7ec27072f8.png)

**Expected behavior**
It should bring you to the tag edit page.

**System Information:**
 - OS: Windows 10
 - Affected App Version: =<0.8.1-alpha

**Comment by Sandakan** [comment]
I was thinking of not showing id3 tags for songs outside the library. The blank page is a side effect of that.
I think I should reconsider that.

**Comment by JustCallMeQuincy** [comment]
Thanks! I think it'd be handy to see the tags, even whilst playing outside of the library.

**Comment by JustCallMeQuincy** [comment]
Confirmed
