### ISSUE TITLE
False tags from songs outside of library

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#112]
**Describe the bug**
When opening a song from outside of the library, some tags may show false values.

**To Reproduce**
1. Open a song outside of your library
![image](https://user-images.githubusercontent.com/71931404/218534359-b9ce91bb-3535-43b0-ab64-b9945d1f77ab.png)

**Actual tags: (Mp3Tag)**

![image](https://user-images.githubusercontent.com/71931404/218534486-e4e68efc-d217-48e9-97dc-d72cc742325e.png)

**Expected behavior**
Should show all tags like embedded into the file.

**System Information:**
 - OS: Windows 10
 - Affected App Version: =<0.8.1-alpha

**Comment by Sandakan** [comment]
What metadata can you see on the app?
I intentionally skipped some metadata such as comments since I thought they wouldn't be much of use.

**Comment by JustCallMeQuincy** [comment]
Well, like in the previous issue, none, though here I'm talking about the artist being shown as "Unknown artist".
