### ISSUE TITLE
Dark mode for "Add Folder" button

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#115]
**Describe the bug**
The button's text is white, while the button's color is light. It would look better with dark text.

**Screenshots**
![image](https://user-images.githubusercontent.com/71931404/221379563-540c6101-5fde-487e-ae75-be8f9ac5ac52.png)

**System Information:**

- OS: Windows 10
- Affected App Version: 1.0.0

**Additional context**
Some buttons may have the same issue. It's just cosmetic but it may be of interest to change it.

**Comment by JustCallMeQuincy** [comment]
It feels like I'm only pointing out the flaws, but I try to help as much as I can to make this the best music software out there.

You're doing an amazing job. Truly.

**Comment by Sandakan** [comment]
I appreciate what you are doing.
I fixed that button's text contrast issue for the upcoming update. If you find anything like that, please don't hesitate and let me know. 💪💪
