### ISSUE TITLE
Lyrics in mini player

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#117]
**Describe the bug**
Non-synced lyrics in the media player cannot be scrolled.

**To Reproduce**

1. Enable mini player
2. Enable lyrics

**Expected behavior**
Not sure if non-synced lyrics should be shown, since scrolling would be better set to control the volume.

**Screenshots**
![image](https://user-images.githubusercontent.com/71931404/221393362-cf39ea37-f997-412c-8006-423c53dd96e8.png)
![image](https://user-images.githubusercontent.com/71931404/221393366-c8ef7e04-beb9-41ba-ad17-c9dbe6bfc9d9.png)

**System Information:**

- OS: Windows 10
- Affected App Version: 1.0.0-stable

**Comment by Sandakan** [comment]
What if I only show lyrics in the `Mini Player` if the song only has synchronized lyrics?
If it only has unsynced lyrics, a message saying `No Synced Lyrics Found` is displayed instead of the unsynced lyrics.

**Comment by JustCallMeQuincy** [comment]
That sounds like it would fix the issue :)

**Comment by JustCallMeQuincy** [comment]
Confirmed
