### ISSUE TITLE
Ability to see full list of entries in `Recently Added` and -`Played` tabs

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#118]
**Is your feature request related to a problem? Please describe.**
I noticed that you can only view a small amount of entries in the `Recently Added Songs` and `Recently Played Songs` categories.

**Describe the solution you'd like**
I think it'd be nice to have a button to "See All" entries, which brings you to a list of all entries.

The previews are nice, though I think this would be a great addition.

![image](https://user-images.githubusercontent.com/71931404/221393610-cbff8170-5ff5-42a2-9df4-685e34523f6e.png)

**Comment by JustCallMeQuincy** [comment]
Addition:

These lists already exist, so the `See All` buttons would just bring you to those lists.

**Comment by Sandakan** [comment]
I think what you mean is something like this.
- When I click the `see all` button in the `Recently Added Songs` section, I should be navigated to the `Songs` page with the sort mode set to `Newest`.
- And when I click the `see all` button in the `Recently Played Songs` section, I should be navigated to the `History` playlist on the `Playlists` page.

**Comment by Sandakan** [comment]
I was actually following the Oto Music app's way of showing the recent items on its Home page.
The only difference is in Oto Music, it can be scrolled. I didn't add the scroll bar because it looks a bit ugly to have a horizontal scroll bar on the Home page.

**Comment by JustCallMeQuincy** [comment]
Oh I see, well I tried scrolling it and it didn't work for me, hence why the suggestion.

**Comment by JustCallMeQuincy** [comment]
> I think what you mean is something like this.
> 
>     * When I click the `see all` button in the `Recently Added Songs` section, I should be navigated to the `Songs` page with the sort mode set to `Newest`.
> 
>     * And when I click the `see all` button in the `Recently Played Songs` section, I should be navigated to the `History` playlist on the `Playlists` page.

That's how it would work, indeed.
