### ISSUE TITLE
Visual bug in Search tab

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#120]
**Describe the bug**
When searching I encountered this *seemingly random*  bug.
It only happens with songs that I have previously removed then pasted again into my music folder.
The music app has been restarted before this bug happened.

**Screenshots**
![image](https://user-images.githubusercontent.com/71931404/221394699-e766ccb6-b6b0-461a-b08e-88685bea688b.png)
![image](https://user-images.githubusercontent.com/71931404/221394696-8a323bc4-2fbc-4357-ba0a-2958e1a6b465.png)

**Log File**
[logs.txt](https://github.com/Sandakan/Nora/files/10833058/logs.txt)

**System Information:**

- OS: Windows 10
- Affected App Version: 1.0.0-stable

**Additional context**
![bug-GIF](https://user-images.githubusercontent.com/71931404/221394788-2e1215d0-4be8-484b-a12e-fbecc1e78269.gif)

**Comment by JustCallMeQuincy** [comment]
In addition:

These songs are missing a cover image, though the file does indeed contain it.

![image](https://user-images.githubusercontent.com/71931404/221394899-4d9656e6-b53d-4e68-b4fc-f4653643c317.png)

**Comment by JustCallMeQuincy** [comment]
After a few application restarts, the covers started showing again in the app.

I'm leaving the issue open as it may require some investigating in why this behavior occurred.

**Comment by Sandakan** [comment]
I think the image is trying to reload itself and fails continuously. 
The broken image reloading bug will be fixed in the next update.

**Comment by Sandakan** [comment]
In each restart, the app looks for any song that hasn't been added to the library but is in the linked folder. Maybe that process fixed this bug temporarily.

But right now, I can't come to a conclusion as to why that happened to begin with.

**Comment by JustCallMeQuincy** [comment]
Yeah me neither, it hasn't happened to me before this occurrence.
