### ISSUE TITLE
Visual bug in `Songs` tab

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#121]
**Describe the bug**
When cover art is non-square, the order-number of the song shifts to the left, making it misaligned with the rest.

**Screenshots**
![image](https://user-images.githubusercontent.com/71931404/221395073-1227ae00-a23f-4e98-b294-f194d8b71a57.png)
![image](https://user-images.githubusercontent.com/71931404/221395075-e67f1b0f-7d0e-4d1e-b6b1-ce40e28d29e8.png)

**Comment by Sandakan** [comment]
I added a fix for this bug for the next update.
Please let me know if you still see this bug in the next update.

**Comment by JustCallMeQuincy** [comment]
Should be fixed in #114

**Comment by JustCallMeQuincy** [comment]
Confirmed 

![image](https://user-images.githubusercontent.com/71931404/221421363-f116d720-f17c-4143-8209-ffe662ee11aa.png)
![image](https://user-images.githubusercontent.com/71931404/221421359-c5dfbf99-8d19-41ad-990e-f457c474bc69.png)

**Comment by Sandakan** [comment]
Thanks for the update
