### ISSUE TITLE
All music in `Blacklisted Songs` tab

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#122]
**Describe the bug**
Without adding any blacklisted songs, all of the music in my music folder is in the `Blacklisted Songs` tab. The songs play, though this must be a mistake.
Any songs blacklisted afterwards get added at the back of the list.

**Expected behavior**
This should contain the songs that were blacklisted, in this case none.

**Screenshots**
![image](https://user-images.githubusercontent.com/71931404/221395171-75fb2c8b-68a2-4bbb-b6fc-63983d8af764.png)
![image](https://user-images.githubusercontent.com/71931404/221395161-d4ece418-89b6-4c59-90a5-60fcc984ad11.png)

**Log File**
[logs.txt](https://github.com/Sandakan/Nora/files/10833093/logs.txt)

**System Information:**

- OS: Windows 10
- Affected App Version: 1.0.0-stable

**Comment by Sandakan** [comment]
Thanks for pointing out that bug.
I unwillingly fixed it improving how blacklisting works.
And I also removed the `Blacklisted Songs` section in the `Settings` and added a sort option to the `Songs` section to remove confusion about the blacklisting.

**Comment by JustCallMeQuincy** [comment]
Confirmed, though you may need to change the help text in the popup:

![image](https://user-images.githubusercontent.com/71931404/221422280-8d29ee94-6754-46f8-9bd6-9546b24b4e25.png)

@Sandakan

**Comment by Sandakan** [comment]
Oh yeah, my bad 🤦‍♂️
