### ISSUE TITLE
Songs with unknown title

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#124]
**Describe the bug**
When a song doesn't have a title in its metadata, it shows as `unknown title`.
![image](https://user-images.githubusercontent.com/71931404/221421826-5f34164d-fb37-42bd-b95d-66957f360b2a.png)

**Expected behavior**
The filename should be shown.

**Screenshots**
(No metadata, except for the cover image)
![image](https://user-images.githubusercontent.com/71931404/221421763-72d8dc0d-154e-4f45-9832-2eeaa50518a1.png)

**Comment by Sandakan** [comment]
That's actually a good idea.
If a song's title tag is empty then I can use the audio file's name as the display title of the song.

**Comment by Sandakan** [comment]
From the first image that you attached, I think this only happens when a song is played outside the library.

**Comment by JustCallMeQuincy** [comment]
It should be possible to make it display the filename for songs outside of the library, right?
