### ISSUE TITLE
More music controls in the mini player

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#126]
**Is your feature request related to a problem? Please describe.**
Using a mini player a lot, while multitasking, has made me aware of the lack of (especially) volume control in the mini player.

**Describe the solution you'd like**
Adding a volume rocker would allow for adjustment of the volume while using the mini player, and wouldn't require you to go back to the main app to adjust the volume.

**Additionally**
Other buttons aren't as necessary for me personally, though I could see how it would increase productivity if all controls would be available in the mini player.

**Comment by Sandakan** [comment]
You could use the keyboard shortcut `Ctrl + Up Arrow' to increase the volume and `Ctrl + Down Arrow` to decrease the volume.

I don't see a position in the mini-player to put another scrollbar without cluttering the whole UI. (suggestions welcome)

**Comment by JustCallMeQuincy** [comment]
Perhaps putting it in the top left, to make it symmetrical with the buttons?
Or you could perhaps add it to the right, and have only the icon show until you hover over it.
![image](https://user-images.githubusercontent.com/71931404/221489188-516b7b48-75fc-4675-aeec-e05f12baf01d.png)

I could get used to the shortcut, though I think that finer control is nice.

**Comment by JustCallMeQuincy** [comment]
In addition to last comment:

The reason I'm so keen on using the scrollwheel is because with multiple monitors, while multitasking, using the scrollwheel on an inactive window doesn't unfocus the active window.

**Comment by JustCallMeQuincy** [comment]
If you don't feel like adding a volume rocker to the mini player, maybe you could still implement the scrolling functionality for volume?
Just an idea.. "Scroll anywhere to adjust the volume"

@Sandakan

**Comment by Sandakan** [comment]
![Screenshot (852)](https://user-images.githubusercontent.com/45460443/222067580-2cdb7a04-9c6a-4785-8381-ffa7ef99bb15.png)

@JustCallMeQuincy  I added audio controls to the mini-player.
But it only appears when hovered over the title.
You will be able to enjoy this feature from the next update.

**Comment by JustCallMeQuincy** [comment]
Yay! Thanks! Awesome work
