### ISSUE TITLE
Issue with synced lyrics

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#127]
**Describe the bug**
When changing the lyrics through the tag editor in the app, the song's start seems to get cut off, making any synced lyrics out of sync.
A restart fixes this.

**To Reproduce**

1. Play a song
2. Right-click the name
3. Click on `Edit song tags`
4. Edit the lyrics and save
5. The song's start is now cut off, skipping the song will not fix this.

**Expected behavior**
The song should not cut off.

**System Information:**

- OS: Windows 10
- Affected App Version: 1.1.0-stable

**Comment by Sandakan** [comment]
@JustCallMeQuincy  I don't understand what you mean by the song getting cut off

**Comment by JustCallMeQuincy** [comment]
The first few seconds of the song don't play, even though the timestamp is 0.
It seems as though it shifts past 0.

**Comment by Sandakan** [comment]
I'm sorry, but I couldn't reproduce the bug you mentioned.

I tried to reproduce the bug by following the steps you mentioned. but the audio is playing as expected after saving the lyrics for the song.

I'd appreciate it if you could send a video clip of the bug occurring to my email sandakannipunajith@gmail.com.

**Comment by JustCallMeQuincy** [comment]
I'll re-test, it could be a one-time thing or something very specific.

**Comment by JustCallMeQuincy** [comment]
A second test makes me believe that this must've been some sort of fluke. 
I also can't re-create it anymore.
