### ISSUE TITLE
UI looks stretched when opened in high resolution displays

### ISSUE THREAD

**Issue by Sandakan** [Sandakan/Nora#128]
**Describe the bug**
I found out that the app doesn't look good in high-resolution displays than in low-resolution displays after seeing the app in one of the screenshots provided by @JustCallMeQuincy.
![bug-GIF](https://user-images.githubusercontent.com/71931404/221394788-2e1215d0-4be8-484b-a12e-fbecc1e78269.gif)

**To Reproduce**

1. Open the app on a high-resolution computer.

**Expected behavior**

**Screenshots**
An unstitched with correct margins, padding, and elements at their correct positions.

**Comment by JustCallMeQuincy** [comment]
To be fair, I only set the app to maximized for the purpose of that gif.
Otherwise I keep it in the smaller window with the default dimensions.

**Comment by JustCallMeQuincy** [comment]
Here's a few more views:

1920x1080
![image](https://user-images.githubusercontent.com/71931404/221662320-6e312fa0-27a7-45b1-aeb0-404faf2dc2b6.png)

2560x1440
![image](https://user-images.githubusercontent.com/71931404/221662436-47cb935f-c636-475f-9e2c-8c140f8f6eda.png)

Both screens edge-to-edge (extreme)
![image](https://user-images.githubusercontent.com/71931404/221662557-c2933439-c657-44e2-ae09-f3c19b7b517e.png)

**Comment by Sandakan** [comment]
@JustCallMeQuincy Can you share an image of how you see the app now?

**Comment by JustCallMeQuincy** [comment]
### 2560x1440:

![image](https://github.com/Sandakan/Nora/assets/71931404/8e5c5bd7-5ef3-45b5-a37c-b6fcdeedb38c)
![image](https://github.com/Sandakan/Nora/assets/71931404/3bd94180-8b6f-4af4-a458-a802e2a3e57d)
![image](https://github.com/Sandakan/Nora/assets/71931404/dec0dede-74e2-4d6c-a48c-d250a9bf6c4c)
![image](https://github.com/Sandakan/Nora/assets/71931404/6f6a2173-bc6f-4729-829e-10252bdd5d25)
![image](https://github.com/Sandakan/Nora/assets/71931404/4c8a3da6-0f8a-46fd-8858-895e888d92f8)
![image](https://github.com/Sandakan/Nora/assets/71931404/d55ba198-7c22-43ed-9cd2-4b9dd879825d)
