### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Sandakan** [Sandakan/Nora#137]
Since Nora is an electron program, it should be able to run in Linux out of the box without any additional configurations needed.

![Screenshot from 2023-03-14 06-14-46](https://user-images.githubusercontent.com/45460443/224864552-d675d0b3-084f-4852-8f73-c7bd735a3374.png)

I was able to get it working on an Ubuntu machine. I did some basic testing on the app it worked fine for me.

![Screenshot from 2023-03-14 06-20-57](https://user-images.githubusercontent.com/45460443/224864749-1d1a0553-bd6a-48d2-aac7-bb1bbe57c883.png)

But when I try to package the app for Linux, the electron-builder shows an error message specifically when the program is packaging the deb installer.

Any help is welcome.

**Comment by Sparkplug3000** [comment]
I tried compiling from the instructions, but npm kept giving errors...

**Comment by Sparkplug3000** [comment]
[2023-04-23T15_58_26_714Z-debug-0.log](https://github.com/Sandakan/Nora/files/11304167/2023-04-23T15_58_26_714Z-debug-0.log)
[2023-04-23T15_58_25_736Z-debug-0.log](https://github.com/Sandakan/Nora/files/11304169/2023-04-23T15_58_25_736Z-debug-0.log)
[2023-04-23T15_58_23_239Z-debug-0.log](https://github.com/Sandakan/Nora/files/11304170/2023-04-23T15_58_23_239Z-debug-0.log)

[2023-04-23T15_54_59_229Z-debug-0.log](https://github.com/Sandakan/Nora/files/11304171/2023-04-23T15_54_59_229Z-debug-0.log)



I tried compiling the latest version, npm still gives errors, but here are the logs

**Comment by Sandakan** [comment]
I was actually able to start up the dev build of Nora on Ubuntu. But there are some bugs such as crashing the app when trying to parse the library.
I was also able to build the app as deb package, but the app wouldn't open in my system. since there are no logs related to this issue, I couldn't figure out what went wrong.

@Sparkplug3000 I saw that the node version of your system is v12. Can you try to update to a newer version.

**Comment by Sparkplug3000** [comment]
I'm on PopOS 22.04, it's based on Ubuntu

**Comment by Sparkplug3000** [comment]
Sooo I ran the deb and it's working flawless for now.... (My library is ~1700 tracks, all FLAC) the tags are read just fine, all the album art is there, I haven't spotted any misread tags yet
Funny, I'm not able to build it but it runs fine, dev is getting issues running it but ofc it builds fine lol

**Comment by Sparkplug3000** [comment]
I tried updating my nodejs and here is the error message I got :

_E: /var/cache/apt/archives/nodejs_18.16.0-deb-1nodesource1_amd64.deb: trying to overwrite '/usr/share/systemtap/tapset/node.stp', which is also in package libnode72:amd64 12.22.9~dfsg-1ubuntu3_

**Comment by Sandakan** [comment]
https://github.com/Sandakan/Nora/issues/137#issuecomment-1528853082
@Sparkplug3000, I asked ChatGPT about that error message and it says that you should remove the previous NodeJs installation before installing the newer version. You can use the below command to remove the old NodeJs version.
```bash
sudo apt-get remove nodejs
```
Then install using this command
```bash
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\
sudo apt-get install -y nodejs
```
If you still see the error message, you may need to remove the conflicting file before installing the newer nodejs version.
Check twice before deleting files because deleting the wrong file can break your system.

**Comment by Sparkplug3000** [comment]
@Sandakan Okay, I will try it out

**Comment by Sparkplug3000** [comment]
I've got it compiled, up and running, currently the app is running stable, the few issues of album tags being misread and split into multiple artists that was in the .deb file is not there when I compiled it myself. Will test it further and send logs too.

**Comment by Sandakan** [comment]
From this update onwards, I will add Linux installers for Nora. 
Keep in mind that even though Nora is stable on Windows, it may not be stable on Linux. 
Since I won't be able to test Linux builds on my machine, I will be relying on user feedback for Linux build improvements.

**Comment by Sparkplug3000** [comment]
> From this update onwards, I will add Linux installers for Nora. 
> Keep in mind that even though Nora is stable on Windows, it may not be stable on Linux. 
> Since I won't be able to test Linux builds on my machine, I will be relying on user feedback for Linux build improvements.

Awesome! Can't wait to give it a spin!

**Comment by Sparkplug3000** [comment]
So the album sorting is using the title as well which is causing a little bit of an issue....
![bug 2](https://github.com/Sandakan/Nora/assets/107550531/5f27073c-a58f-4da4-ad47-2a64004f2d7c)

**Comment by Sandakan** [comment]
@Sparkplug3000 Is the second song the same as the first song?

**Comment by Sparkplug3000** [comment]
> @Sparkplug3000 Is the second song the same as the first song?

No, they are different tracks that happen to have the same name.

**Comment by Sandakan** [comment]
@Sparkplug3000  Songs aren't added to albums based on their names. That second song might have had the album name on its metadata. Try editing it by following the below steps.

1. First right click on the second song and click `Edit Song Tags'
2. check whether the song is linked to that album in the Tags editor.
3. If it is linked, un-link it and the song will disappear from the album.

**Comment by Sandakan** [comment]
@Sparkplug3000 Did you install Nora from the installer in the GitHub releases? Does it work properly?

**Comment by Sparkplug3000** [comment]
@Sandakan Yes it was from the installer only. I haven't been able to use it much lately, will update with any bugs with a bit more usage.
