### ISSUE TITLE
New artist & Genre not adding automatically with `Search Metadata on Internet` when saving

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#138]
_Sorry for the long title haha_

**Describe the bug**
When using `Search Metadate on Internet`, and clicking `Save Tags`, the new artist and genre that were fetched don't get saved automatically.
![image](https://user-images.githubusercontent.com/71931404/225153842-8c2f6de1-446c-4e82-b993-cb473b88eeba.png)

**To Reproduce**

1. Edit a song's tags
2. Click on `Seach Metadata on Internet`
3. Click `Save Tags`

**Expected behavior**
The new tags should save

**What actually happens**
The new tags don't get saved, unless saved manually before clicking on `Save Tags`

**Screenshots**
![image](https://user-images.githubusercontent.com/71931404/225154067-0deb2292-9657-4dbd-90bc-d7dd0beee1fb.png)
![image](https://user-images.githubusercontent.com/71931404/225154100-8bae0c89-fd6d-4c9e-af02-be9f5ea5a0db.png)

**System Information:**

- OS: Windows 10
- Affected App Version: 1.2.0-stable

**Comment by JustCallMeQuincy** [comment]
I do understand that part, though I think it'd be better that when clicking `Save Tags` they should be added, as that's a confirmation nothing needed to change.

That would increase the efficiency of the whole process.
If the tag would be wrong, I could change it, but if the tag would be correct, I could just save the tags and go on to the next ones, without needing to approve each individually.

**Comment by Sandakan** [comment]
I could add a confirmation dialog before saving or leaving the page to confirm it's the correct action of the user.
Or else I could update the metadata only when there is an artist with the same name as the added metadata and not update if the artist doesn't exist to prevent duplications of artists with the same names written in different accents and capitalization.

**Comment by JustCallMeQuincy** [comment]
Confirmed!
