### ISSUE TITLE
Bug with saving song tags (astist and genre)

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#141]
**Describe the bug**
When using `Search Metadata on Internet` on a song, but the Artist and/or the Genre already exist(s), then you have to click the `Save Tags` button twice, in order for the artist and/or genre to apply.

**To Reproduce**

1. Go to a song's `Edit song tags` menu
2. Click the `Search Metadata on Internet` button
3. _Artist already exists_
4. Click `Save Tags`

**Expected behavior**
All metadata* tags save

**What actually happens**
All metadata* saves, except for the artist and genre.
To save those, click again.

_*Presumably_

**System Information:**

- OS: Windows 10
- Affected App Version: 1.2.0-stable

**Comment by Sandakan** [comment]
I couldn't reproduce this problem too.

I think the response in https://github.com/Sandakan/Nora/issues/138#issuecomment-1469730496 is valid here too.

**Comment by JustCallMeQuincy** [comment]
Welp me neither, my response in #138 also applies here.
