### ISSUE TITLE
(Feature Request for Nora) FLAC support

### ISSUE THREAD

**Issue by LatroM69** [Sandakan/Nora#142]
I think think the player is really good, design wise. But the problem is, this doesn't support FLAC files. Would be great if it is possible to add support for FLAC.

**Comment by Sandakan** [comment]
I can provide support for FLAC files in Nora.
But some features like metadata editing doesn't support the FLAC extension.
 
I'll try something about this.

**Comment by LatroM69** [comment]
> I can provide support for FLAC files in Nora. But some features like metadata editing doesn't support the FLAC extension.
> 
> I'll try something about this.

Good to hear, take your time!
Cheers.

**Comment by Sandakan** [comment]
> > I can provide support for FLAC files in Nora. But some features like metadata editing doesn't support the FLAC extension.
> > I'll try something about this.
> 
> Good to hear, take your time! Cheers.

But I won't be able to provide support for editing songs in FLAC format until the dependency that I use for editing song tags supports it.

**Comment by JustCallMeQuincy** [comment]
Confirmed!

**Comment by dimostheenis** [comment]
Support for editing flac files would be really useful. Thank you!
