### ISSUE TITLE
Feature Request: Ability to select all or shift+select for easier selection of items within the app

### ISSUE THREAD

**Issue by metronightly** [Sandakan/Nora#143]
Right now if I have to make a big playlist I have to select each and every song one by one. The ability to select all by ctrl+a or selecting multiple items easily by shift+select would be a great addition.

**Comment by metronightly** [comment]
> From v1.0.0-stable onwards, you can use `shift+click` to select multiple elements. But support for different items and tasks may vary. I will improve this feature in each update to provide more support for other tasks.

I meant shift+click to select the 1st item and let's say the 77th item of a folder should also select all the other 75 items in between.

Right now Nora doesn't function like that, we still have to individually select each and every track from a folder or album page or artist page to create a playlist.

**Comment by JustCallMeQuincy** [comment]
Confirmed!
