### ISSUE TITLE
Feature Request: Auto generate a playlist cover based on the songs inside.

### ISSUE THREAD

**Issue by metronightly** [Sandakan/Nora#145]
It would be great to have a playlist cover generated automatically by Nora based on the songs inside it, for aesthetic purpose.

**Comment by JustCallMeQuincy** [comment]
To add onto this: Oto Music (Android) already does this, example below.
It would be really cool if Nora would also do this. 

![image](https://user-images.githubusercontent.com/71931404/226847639-6abaeb13-cccc-42de-a1a3-0c646719075c.png)

**Comment by Sandakan** [comment]
How about this
![image](https://user-images.githubusercontent.com/45460443/228441735-3d8a2b4d-7585-4258-96b1-86818cd2cfdc.png)
![image](https://user-images.githubusercontent.com/45460443/228441770-24333372-c886-4ce4-bbc1-4687760e1094.png)

**Comment by metronightly** [comment]
> How about this ![image](https://user-images.githubusercontent.com/45460443/228441735-3d8a2b4d-7585-4258-96b1-86818cd2cfdc.png) ![image](https://user-images.githubusercontent.com/45460443/228441770-24333372-c886-4ce4-bbc1-4687760e1094.png) 

The white gap between the album covers could be reduced just a bit but I like it, nice work

**Comment by JustCallMeQuincy** [comment]
Confirmed!
