### ISSUE TITLE
Bug in Nora

### ISSUE THREAD

**Issue by Millimeters** [Sandakan/Nora#146]
There is no response after the software double clicks on Windows 10
![Snipaste_2023-03-22_16-23-38](https://user-images.githubusercontent.com/118607170/226842479-ffa1e12e-c6cd-4b78-bdac-e64715ee1916.png)

**Comment by JustCallMeQuincy** [comment]
@Millimeters what exactly is the issue? Do you have more information?

**Comment by Sandakan** [comment]
I will close this issue since there aren't any responses to the fix provided, assuming it fixed the problem.
If the issue persists, please re-open this issue and let me know.
