### ISSUE TITLE
Feature Request for Nora

### ISSUE THREAD

**Issue by JvpkoIsAPlanet** [Sandakan/Nora#148]
**Is your feature request related to a problem? Please describe.**
I am a music production student, I study both the mastering and technical aspects of music - recording, mixing, finalization, everything. Most of my music is in either .wav or .flac (FLAC being my favourite since it's lossless yet almost half the footprint of WAV) but Nora doesn't seem to be able to support FLAC, which is heartbreaking and frustrating. 

**Describe the solution you'd like**
I believe implementation of something to read and play FLAC files would be fantastic - I believe this could be done via implementation of a Codec though I'm sure it isn't as simple as throwing together some lines of code.

**Describe alternatives you've considered**
I've considered making .mp3 copies of all my music, but the time required to do so, the processing and the loss of quality are simply too great for me to consider.

**Additional context**
N/A - Just a simple feature request. My main music player would absolutely be Nora if it could just play and recognize .flac.

**Comment by JvpkoIsAPlanet** [comment]
I do apologise if this an annoying request, but I do feel very strongly about this - to the point I specifically made a github account just to request this feature - this is the one flaw I have with the whole program. My apologies <3

**Comment by Sandakan** [comment]
It's happy to see how much people love this app. Thanks for the request. 
There's good news and bad news.
I was thinking to provide support for the FLAC format along with some other formats. But there will be some limitations.
The most notable is no support for editing metadata in FLAC format since the package I use to edit metadata only support mp3 (MPEG) format.

**Comment by Sandakan** [comment]
The other limitation is the inability to save lyrics or view existing lyrics. Therefore you will only be able to use the online lyrics on FLAC files.

**Comment by JvpkoIsAPlanet** [comment]
I feel like these are both easy to live with limitations, I personalyl think there is a clever solution to the offline lyrics issue regarding FLAC that may be able to be sovled in the future - I have one question though:

Do you think reading + displaying artwork of FLAC files will be easy? I've personally seen some software actually have issues displaying it &/or instability caused by it and wanted to ask if this could be a potential issue for Nora. Thank you for your patience <3

**Comment by Sandakan** [comment]
I tried some songs in FLAC format and I didn't see any issues when displaying artworks.

**Comment by JustCallMeQuincy** [comment]
Confirmed!
