### ISSUE TITLE
Feature Request: Context menu item on the default cover to visit album

### ISSUE THREAD

**Issue by metronightly** [Sandakan/Nora#149]
Double clicking on the cover when playing a song should take us to the album the song belongs to [image](https://user-images.githubusercontent.com/75716685/227641005-e0e3fb76-1fe3-4033-8361-e249155bf4e7.png)
Right now double clicking on the image does nothing, so hopefully adding such a feature won't cause any issues.

**Comment by Sandakan** [comment]
I don't think that's a good idea to double-click to go to the song album. 
I could add a context menu item to go to the song album on right-click.

**Comment by metronightly** [comment]
> I don't think that's a good idea to double-click to go to the song album. I could add a context menu item to go to the song album on right-click.

That works as well, thank you.

**Comment by Sandakan** [comment]
I'll rename the issue title for more clarity.

**Comment by JustCallMeQuincy** [comment]
Confirmed!
