### ISSUE TITLE
A-Z and Z-A sorting inside playlists works in the opposite way. 

### ISSUE THREAD

**Issue by metronightly** [Sandakan/Nora#156]
All 3 (6) types of alphabetical sorting namely: A to Z, Album Name and Artist Name work in the reverse order inside playlists. Selecting A to Z by song name displays all the songs starting with  Z first, and the opposite happens when I select Z to A. The same thing happens when sorting by Album Name and Artist Name.

1. Go to Playlist
2. Click on any playlist
3. Change the sorting method to A to Z (or Album Name/Artist Name A to Z)
4. You'll see that in reality Z to A is applied where songs with Z name will show up at the top.
5. And when you select Z to A, the song with A name will show up instead.

Example: 
![image](https://user-images.githubusercontent.com/75716685/233833286-45500f27-e865-4500-8ff6-fc773225e0f8.png)

App Version: Nora Stable 2.0
Windows 11

**Comment by Sandakan** [comment]
Thanks for pointing that out. I'll fix it in the next update.
