### ISSUE TITLE
Song bar functionality

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#158]
**Is your feature request related to a problem? Please describe.**
Nothing happens when clicking the bottom song bar unless you click on a button.
![image](https://user-images.githubusercontent.com/71931404/233846276-69434490-3cc8-4007-9da0-3aaab52da7fb.png)

**Describe the solution you'd like**
I'd like a useful tab to open (perhaps configurable) when clicking on the bottom bar. This could be the current song queue or song info, etc.
Then if you'd click the bar again it'd go back to the previous menu. 

**Additional context**
YouTube Music has a decent example of the functionality that I'm describing.

**Comment by Sandakan** [comment]
What do you mean by the song bottom bar?

**Comment by JustCallMeQuincy** [comment]
The bar with the song controls on the main player:

![image](https://user-images.githubusercontent.com/71931404/233847629-29755150-4cb1-40fc-a2d5-f839e33ec7eb.png)

**Comment by JustCallMeQuincy** [comment]
@Sandakan is there a fix suggested for this? 👀

**Comment by Sandakan** [comment]
I improved the context menu when right-clicking on the currently playing song cover. But I didn't add it to the whole footer.
