### ISSUE TITLE
Song right-click action for volume bar

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#161]
**Describe the bug**
Upon right-clicking the volume bar
![image](https://user-images.githubusercontent.com/71931404/233850300-222a1ad4-e6f9-41b3-a5f4-4d2f7529d99d.png)
or the time bar
![image](https://user-images.githubusercontent.com/71931404/233850312-dbcd0f25-968f-4960-8fd9-5d71f4292154.png)
the value gets rounded down to a flat number.

**To Reproduce**

1. Play a song
2. Right-click the time bar
3. Hear the song skip back to the last full second

**Expected behavior**
Nothing, or a right-click menu

**System Information:**

- OS: Windows 10
- Affected App Version: 2.0.0-stable

**Comment by Sandakan** [comment]
I don't think that I can change that behavior. I tried to prevent that event from occurring but it didn't change anything.

**Comment by Sandakan** [comment]
I tried to mimic the left-click for the right-click event, but it didn't work.
And I also found on the internet that mimicking events can break accessibility for some users.

**Comment by JustCallMeQuincy** [comment]
I see, well let's just keep this in the background then, since it's not such a big issue
