### ISSUE TITLE
Song artwork missing upon saving metadata

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#162]
**Describe the bug**
Upon saving the `Search Metadata on Internet` results, the album cover shows the fallback, though the new one is present.
After a reload (F5) this is fixed.

**To Reproduce**

1. Edit a song
2. Get metadata from the `Search Metadata on Internet` option
3. Click `Save Tags`
4. See album cover revert to default

**Expected behavior**
Should show new album cover

**Screenshots**
![image](https://user-images.githubusercontent.com/71931404/233851326-df2d0171-a004-468e-88df-ad1f2cf9bfd1.png)
![image](https://user-images.githubusercontent.com/71931404/233851325-11e86015-0e39-43ad-8d76-c39b2043bda0.png)

After reload:
![image](https://user-images.githubusercontent.com/71931404/233851349-47c02e7f-573e-4fdd-b005-4ee619389f15.png)
![image](https://user-images.githubusercontent.com/71931404/233851352-bd01ad96-1de5-43fa-9967-801177bbe8ba.png)

**System Information:**

- OS: Windows 10
- Affected App Version: 2.0.0-stable

**Comment by JustCallMeQuincy** [comment]
Also had this happen once:
![image](https://user-images.githubusercontent.com/71931404/233851497-47134358-a854-4290-b1da-9e55d0b528cf.png)

**Comment by JustCallMeQuincy** [comment]
They do indeed render in the `Currently Playing Queue`
![image](https://user-images.githubusercontent.com/71931404/233852274-fdd58aa0-ffc0-47d4-91d5-1f1f4b7a44fa.png)

**Comment by JustCallMeQuincy** [comment]
Well I'm at a complete loss. 

The app won't add artworks for *some* songs, so if I manually add artwork through a different app it's actually applied, but for (again) *some* songs this won't show up in the app.

![image](https://user-images.githubusercontent.com/71931404/233864676-d3d5cc0b-b450-4c6a-8c19-a649f29ad3da.png)
Same song in MP3Tag
![image](https://user-images.githubusercontent.com/71931404/233864702-9e7272a6-7368-45b7-85f8-7e5061e67f9d.png)

**Comment by JustCallMeQuincy** [comment]
Log file:
[logs.txt](https://github.com/Sandakan/Nora/files/11304877/logs.txt)

**Comment by JustCallMeQuincy** [comment]
A hard reset of the app did the trick
![image](https://user-images.githubusercontent.com/71931404/233865040-87136745-fdc5-4afd-b2fe-771a549fcb82.png)

**Comment by Sandakan** [comment]
https://github.com/Sandakan/Nora/issues/162#issuecomment-1519105683
This bug happens due to image caching issues in the app. That's why when you reload the app, it shows the correct artwork. I added some fixes for this in v2.0 but seems like it didn't work. I'll try something new for this.

In https://github.com/Sandakan/Nora/issues/162#issuecomment-1519150022,
Nora doesn't get triggered when you use another app to modify song metadata in the library.
But I think it could be a feature worth adding to Nora.

**Comment by JustCallMeQuincy** [comment]
@Sandakan is there a fix planned for this?

**Comment by Sandakan** [comment]
I still haven't decided how to fix the caching issue and provide support for the external modification trigger.

**Comment by Sandakan** [comment]
@JustCallMeQuincy do you still see issues related to this project or is that a random issue you found in the app?
If it is random, then I can focus more on other issues.

**Comment by JustCallMeQuincy** [comment]
It's persistent, in a way, as I've had one of my songs just completely break once when editing the lyrics (couldn't re-create it sadly)
@Sandakan

**Comment by Sandakan** [comment]
@JustCallMeQuincy What do you mean by "one of my songs just completely break"?

**Comment by JustCallMeQuincy** [comment]
All of the tags got removed and it could not be played anymore, even after a full restart.
@Sandakan

**Comment by JustCallMeQuincy** [comment]
I'll re-open the issue if I come across this issue again. From my limited testing it seems fixed.
