### ISSUE TITLE
BREAKS NORA - Mini-player bug

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#163]
**Describe the bug**
When enabling the Mini-player, making it "full-screen" and restoring the window to a "non-full-screen" state, the app hard-crashes.
This even reset the app for me on multiple occasions

**To Reproduce**

1. Play song (optional)
2. Open in Mini-Player
3. Set Mini-Player to full-screen mode (drag to the top of the screen and let go, or double-click the top of the window)
4. Take the Mini-Player out of full-screen mode (drag away from the top of the screen)
5. Crash

**Expected behavior**
The Mini-Player should not be able to be set to full-screen mode.
It should not crash.

**Screenshots**
![Bug-GIF-4](https://user-images.githubusercontent.com/71931404/233865774-ec93c33a-a57b-4e09-8ed3-df2b3fe5cf53.gif)

**Log File**
[logs.txt](https://github.com/Sandakan/Nora/files/11304929/logs.txt)

**System Information:**

- OS: Windows 10
- Affected App Version: 2.0.0-stable

**Comment by Sandakan** [comment]
Thanks for pointing it out.
I found out that it is a bug in electron and i created an issue in their repo.
https://github.com/electron/electron/issues/38098

**Comment by Sandakan** [comment]
@JustCallMeQuincy, 
> This even reset the app for me on multiple occasions

I saw this now. Did the app reset by itself after the crash?

**Comment by JustCallMeQuincy** [comment]
@Sandakan iirc, yes. Though only on some occasions
