### ISSUE TITLE
Media keys

### ISSUE THREAD

**Issue by LandStander27** [Sandakan/Nora#166]
**Describe the bug**
When I use media keys (pause, fast forward, rewind), they don't do anything.

**To Reproduce**

1. Open Nora.
2. (For most keyboards) Hold FN key and press the F key with a pause symbol on it.

**Expected behavior**
For the song to pause.

**System Information:**

- OS: Windows 11
- Affected App Version: 2.0.0

**Comment by JustCallMeQuincy** [comment]
The media keys work for me.
I do, however, use a full-sized keyboard, not a laptop one, so I don't need to hold the `Fn` key.
I'd think this doesn't make a difference, but it could be possible

**Comment by Sandakan** [comment]
@LandStander27 Does this happen when the app is focused or not?

**Comment by LandStander27** [comment]
> @LandStander27 Does this happen when the app is focused or not?
> 

It happened both ways.

**Comment by LandStander27** [comment]
Just tried it today and it seems to be working for some reason, sorry for wasting your time.
