### ISSUE TITLE
More Custom Playback speed with hotkey to adjust the speed

### ISSUE THREAD

**Issue by ms-2525** [Sandakan/Nora#168]
Hi,
Can you add more custom playback speed to the player?
I want to be able to change the speed by say x0.05 or x0.1 

Currently i use VLC for playing audio files too as in VLC we can increase the speed by x0.05 and also assign a hotkey to control the playback. I have assigned "[" "]" to decrease and increase the speed and "\" to reset the speed to 1x
My default playback speed is 1.25x

If this can be implemented in Nora, then it would be wonderful

Thank you

**Comment by JustCallMeQuincy** [comment]
I think generally an tab in the settings menu where you can change/adjust hotkeys would be quite handy.

**Comment by JustCallMeQuincy** [comment]
For speed, I'd perhaps go for `ctrl + scroll` as that's currently unused
Alternatively, we could go for a combination involving `+` and `-`
If that doesn't work, `PgUp` and `PgDn` could work
