### ISSUE TITLE
Bug - Nora does not respect song order/index metadata

### ISSUE THREAD

**Issue by Neptune-mk2** [Sandakan/Nora#169]
**Describe the bug**
Nora does not respect the order in which a song is to be played when metadata includes a track number regardless of the indexing option being turned on or off.

This has been tested in both .mp3 files and .flac, indexing enabled in Nora.

**To Reproduce**

1. (optional) Go to settings and enabling indexing
2. Play an album of your choice or add a album from a folder to the queue
3. Go to the queue and compare the song order to the song order in your file explorer
4. Song order will not match

**Expected behavior**
Albums played or folders added to the queue should respect the play order/index metadata unless shuffle is enabled.

Bellow is a screenshot comparing song order in Nora and song order in file explorer with the metadata showing its respective order.
**Screenshots**
![image](https://user-images.githubusercontent.com/34612088/236986706-a9480f5c-7001-4b7d-a0bb-0bfd05023d76.png)

**Log File**
N/A - Not applicable

**System Information:**

- OS: Windows 11 Pro - 22621.1635
- Affected App Version: 2.0.0 Stable

**Additional context**
As stated above this issue affects most if not all file formats, I have only tested it with .mp3 and .flac, I suspect if this is not implemented yet or intended behavior it is likely being caused by the song ordering being overridden by the sorting order.

Also not related to the issue at all, I wanted to add my appreciation for your work on this music player, I'm very impressed by the visuals of Nora and overall performance. I've been looking for a new music player for quite a while now and the initial impressions are very good, I see lots of untapped potential! Only thing else I'd like to add is its unfortunate there is no way to change the accent color from just light blue, hopefully you can find a way around the problem so this could be a possibility in the future.

**Comment by Sandakan** [comment]
@Neptune-mk2
Thanks for your honest opinion of Nora.

I think you are correct to assume that I didn't implement this feature for Nora. I didn't know there should be functionality like this for the disc number.
To verify this functionality, the song order should be followed only in albums, right?

**Comment by Neptune-mk2** [comment]
> To verify this functionality, the song order should be followed only in albums, right?

Yes, at least in its usual use case Albums is where you would want a song to play in a specific order because some songs may include specific tracks like a "intro/outro" or are meant by the album artist to tell a "story", without the track order the album may not play as intended by the album artist.

In other occasions though you might want to keep song order outside of albums, as an example if you want to make a playlist with different albums but want them to play in their original order.

I'm not very technical when it comes to programming, but I imagine doing this would also require figuring out problem like "How would it handle multiple songs with the same track number"

To that I did have a rough idea on how that could be resolved not sure if this is how it works but, maybe you can check the metadata for album name first then track number to derive the play order.

This way even if you have multiple songs with track number 1, but it would first prioritize the album name first then the track number.

So album sorting would retain the A-Z order then track number order unless shuffle is specified or any other sorting method is selected.

**Comment by Sandakan** [comment]
@Neptune-mk2 
Maybe I can add a new sorting option for albums as the default sorting option which sorts the songs in an album according to their track number.
But since I currently don't save the track number for each song, for this feature to take effect you should reset the app.

**Comment by Sandakan** [comment]
@Neptune-mk2 
Maybe I can add a new sorting option for albums as the default sorting option which sorts the songs in an album according to their track number.
But since I currently don't save the track number for each song, for this feature to take effect you should reset the app.

**Comment by Neptune-mk2** [comment]
That sounds like a great idea, much simpler than the way I though of.

Looking forward to it 😄

**Comment by Sandakan** [comment]
But there's another problem.
Then the user has to go to the `Album Info Page`, select the `Track Number` as the sorting option, and then select `Play All` for this to work. This won't work when you right-click on an album and select `play`.

**Comment by Neptune-mk2** [comment]
Oh I see, I'm not quite sure what would be the best way to handle that.

The way other music players handle it by default they sort by track number when inside the album, VLC also seems to do this.

Maybe the sorting option might have to be a option default that can be changed in settings, if that doesn't work I'm afraid I'm out of ideas.

**Comment by Sandakan** [comment]
For the time being I will implement the feature as I mentioned before.
If it's not working as expected, you can mention me again about it.

**Comment by MikeeSierrah** [comment]
hi - can you add this sorting option to folders too?
