### ISSUE TITLE
Artist name's font color transition from default to adaptive color is slow.

### ISSUE THREAD

**Issue by metronightly** [Sandakan/Nora#174]
When I visit an artist's page, the font color for their name stays as this very light blue color for a second or so 
![(Example)](https://github.com/Sandakan/Nora/assets/75716685/8f4aaa18-6b38-401a-a717-532a44e87895)
before adapting ![(Example)](https://github.com/Sandakan/Nora/assets/75716685/48a8ea2f-2e22-4f18-8663-6654d9847b63) to a color from the artist's profile photo

I have disabled background artists, and enabled reduced motion as well.

It would be great if this transition of blue color to the adaptive color was instant.

**Comment by Sandakan** [comment]
It's not an animation I put in the app. The app takes some time to parse the artist's image to find a proper color for the text. That's why the font color changes after some time. 
But I will change the default text color from light blue to dark blue for better visibility.
