### ISSUE TITLE
Nora unable to play some flac files

### ISSUE THREAD

**Issue by metronightly** [Sandakan/Nora#184]
Nora is unable to play some flac files that are perfectly playable on VLC 4 (windows) and Oto Music as well. Here's an example of flac file: https://file.io/TkXd7aLSkiM9

I have tried uninstalling Nora 2.2.0 and reinstalling, and reset app but to no avail. Upon playing such songs it looks like this: 
![image](https://github.com/Sandakan/Nora/assets/75716685/d0e3c669-5cb9-4e80-b7f9-c6974d75a4e5) the play/pause button doesn't respond, it acts like the file is dead even though it isn't.

App version: Nora 2.2.0 Stable
Windows 11 Home

**Comment by metronightly** [comment]
> @metronightly It seems like your song is corrupted but playable in some audio players. (Maybe during a conversion process) if you have the resources, can you download the same music in Flac and try to play it on Nora?

This was the flac version that I downloaded from deezer bot on telegram.

**Comment by Sandakan** [comment]
@metronightly 
I tried to play that song in Edge (Chromium) and it can't play that song, but it plays on Firefox. So it seems like the bug is in the Chromium project since Nora uses it under the hood.
Is this the only song that can't be played?

**Comment by metronightly** [comment]
> @metronightly I tried to play that song in Edge (Chromium) and it can't play that song, but it plays on Firefox. So it seems like the bug is in the Chromium project since Nora uses it under the hood. Is this the only song that can't be played?

Yeah there were many other files like this. They were untouched-unedited flacs downloaded from deezer apparently, but I tried a tag editor on those files and now Nora can play them.

If you use a tag editor app like automatic tag editor from playstore to edit some tags on your file then maybe Edge would be able play the song too. This could possibly help identify the exact issue.
