### ISSUE TITLE
Feature Request for Nora

### ISSUE THREAD

**Issue by Chen1Plus** [Sandakan/Nora#189]
Nora doesn't support **.m4a** files.

Hope adding support to **.m4a** files.

**Comment by Sandakan** [comment]
@Chen1Plus,
Nora is powered by Electron which internally depends on the Chromium framework. It only includes codec files for songs in fewer formats.
- mp3
- wav
- ogg
- aac
- m4r
- flac

So, I don't think that Nora will be able to support songs in m4a format.
Sorry to disappoint you. 😪
