### ISSUE TITLE
PIPELINE_ERROR (Nora)

### ISSUE THREAD

**Issue by BijSvenNL** [Sandakan/Nora#190]
**Describe the bug**

(Build created with building it with Node JS)

**To Reproduce**

1. Go to 'a number'
2. Click on 'play'
3. See error

**Expected behavior**

**Screenshots**

**Log File**
CODE 3 : PIPELINE_ERROR_DECODE: Unsupported midstream configuration change! Sample Rate: 48000 vs 48000, Channels: 2 vs 1

**System Information:**

- OS: Windows 11 Home 22621.1992
- Affected App Version: v2.3.0-stable

**Additional context**
Numbers just worked fine. After adding metadata they didnt work again :(

**Comment by Sandakan** [comment]
@BijSvenNL,
First, what do you mean by `Go to a number`?
From the error `CODE 3: PIPELINE_ERROR_DECODE`, it seems like the song is corrupted. Does Nora play other songs correctly?

**Comment by BijSvenNL** [comment]
Play s audio file.

**Comment by BijSvenNL** [comment]
> @BijSvenNL,
> First, what do you mean by `Go to a number`?
> From the error `CODE 3: PIPELINE_ERROR_DECODE`, it seems like the song is corrupted. Does Nora play other songs correctly?

All the songs are played correctly but when you setup metadata via the gui it corrupts the song

**Comment by Sandakan** [comment]
@BijSvenNL,
What is the extension of the song that got corrupted? (Ex: mp3)
What fields did you edit?
Were you playing the same song when you edited it?

**Comment by BijSvenNL** [comment]
It is a mp3 file
I edit the author and the cover image name etc. Just via search metadata option

**Comment by Sandakan** [comment]
There is no author in the Nora app's metadata fields. Did you mean the `Composer` field?
If you edited the current playing song, maybe it is the reason for the corruption. If you don't mind, can you try editing songs while not playing them to see whether it still corrupts the song?

**Comment by BijSvenNL** [comment]
The one who sang the song. It's under the title of the song, isn't it?

**Comment by BijSvenNL** [comment]
The one who sang the song. It's under the title of the song, isn't it?

**Comment by BijSvenNL** [comment]
> There is no author in the Nora app's metadata fields. Did you mean the `Composer` field?
> If you edited the current playing song, maybe it is the reason for the corruption. If you don't mind, can you try editing songs while not playing them to see whether it still corrupts the song?
> 
>  

On this moment i dont have access to my desktop :( ( I am sorry)

**Comment by Sandakan** [comment]
> > There is no author in the Nora app's metadata fields. Did you mean the `Composer` field?
> > If you edited the current playing song, maybe it is the reason for the corruption. If you don't mind, can you try editing songs while not playing them to see whether it still corrupts the song?
> 
> On this moment i dont have access to my desktop :( ( I am sorry)

Its ok, let me know when you have the time. 👍

**Comment by BijSvenNL** [comment]
> > > There is no author in the Nora app's metadata fields. Did you mean the `Composer` field?
> > > If you edited the current playing song, maybe it is the reason for the corruption. If you don't mind, can you try editing songs while not playing them to see whether it still corrupts the song?
> > 
> > On this moment i dont have access to my desktop :( ( I am sorry)
> 
> Its ok, let me know when you have the time. 👍

Thank you, your the best!

**Comment by BijSvenNL** [comment]
@Sandakan, I am back but that doesn't help. When you change the metadata when you are not playing the song.

**Comment by BijSvenNL** [comment]
![image](https://github.com/Sandakan/Nora/assets/96389299/2d505274-46ec-4bfd-84e4-4f6a97fa6409)

**Comment by Sandakan** [comment]
@BijSvenNL ,
Is that the same song that you mentioned in before or did you try to edit the metadata of a new song and try to play it?
Does VLC play it correctly without any errors?
`MediaImage src exceeds maximum URL length` occurs when the song artwork size is larger and it is not the reason for this kind of behaviour.
Does other songs that you didn't edit metadata play fine?

**Comment by BijSvenNL** [comment]
![image](https://github.com/Sandakan/Nora/assets/96389299/1b7d60f3-0104-4d8d-8168-3907e8c08fb9)

**Comment by Sandakan** [comment]
@BijSvenNL, Did that error occur when you are playing an mp3 file or a FLAC file?

**Comment by BijSvenNL** [comment]
> @BijSvenNL, Did that error occur when you are playing an mp3 file or a FLAC file?

Mp3

**Comment by BijSvenNL** [comment]
@Sandakan its weird that it does that. because and all the other media players play it correctly even when i add metadata via my own script!

**Comment by metronightly** [comment]
Don't know about pipelines or whatever but I have the same issue: https://github.com/Sandakan/Nora/issues/184

![image](https://github.com/Sandakan/Nora/assets/75716685/a8f62b0d-bdda-43e8-8077-ad169fc35e22)

**Comment by Sandakan** [comment]
> Don't know about pipelines or whatever but I have the same issue: #184
> 
> ![image](https://user-images.githubusercontent.com/75716685/258116528-a8f62b0d-bdda-43e8-8077-ad169fc35e22.png)
> 
> Mine happens only on FLAC files though.

Seems like Chromium doesn't include relevant codecs to play some specific FLAC files.

did you able to play that FLAC song earlier from Nora?
Does that song work on other audio players?

**Comment by metronightly** [comment]
> Seems like Chromium doesn't include relevant codecs to play some specific FLAC files.
> 
> did you able to play that FLAC song earlier from Nora? Does that song work on other audio players?

Not just that but Nora can't seem to play 30% of my songs since I moved my entire library from mp3s to flacs. Other players on windows like vlc, windows media player, musicbee can play those songs fine. On android, oto music, nyx, retro music etc can also play those files. I wish I could help identify the root cause but it's probably chromium like you said.

**Comment by metronightly** [comment]
> Are those other songs also showing the same error message?

Yes, about 150-200 of the 600 flac files I have seem to have this issue.
