### ISSUE TITLE
Bug in Nora - Duplicate "Appears On Albums" Tiles

### ISSUE THREAD

**Issue by RichardKanshen** [Sandakan/Nora#191]
**Describe the bug**
Each song by an artist shows up as a different album in "Appears on Albums", even though it is just one album

**To Reproduce**

1. Have multiple songs by the same artist on the same album
2. Go to the artist's page

**Expected behavior**

- Just one tile per album
and possibly
- A separate row for albums by the artist, and a separate for guest appearances

**Screenshots**
![image](https://github.com/Sandakan/Nora/assets/73738591/ad008819-2b5f-467c-99df-147985469aac)

**Log File**
N/A - This seems to be an oversight in the code.

**System Information:**

- OS: Windows 10
- Affected App Version: Appeared in both 2.2.0-stable and 2.3.0-stable

**Comment by Sandakan** [comment]
@RichardKanshen,
It's a bug in Nora's database.
Could you please tell me whether you use Nora's suggestions to modify song metadata? If so, did you see this behavior after using that service?

**Comment by RichardKanshen** [comment]
I have seen this behaviour without using the metadata editor in Nora.

**Comment by Sandakan** [comment]
@RichardKanshen,
I meant suggestions like this
![suggestions-light](https://github.com/Sandakan/Nora/assets/45460443/7678fac1-c26c-4769-9cce-1d390b853034)

**Comment by RichardKanshen** [comment]
Nope, I did not use that one either.

**Comment by Sandakan** [comment]
@RichardKanshen,
I found a fix for this bug.
I'll fix it in the next update
Thanks for letting me know

**Comment by RichardKanshen** [comment]
Just updated, it looks so much cleaner now, thanks a lot!
