### ISSUE TITLE
Bug in Nora - Odd audio glitch

### ISSUE THREAD

**Issue by RichardKanshen** [Sandakan/Nora#192]
**Describe the bug**
The audio sometimes rewinds a couple of seconds. Not on the timeline, just the audio. This also results in the song ending before the audio does.
*Note:* This does not get fixed after rewinding back on the timeline manually, it kind of corrupts the temporarily loaded version of the file.

**To Reproduce**

1. Play a song
2. Occasionally, the audio rewinds for no reason.

**Expected behavior**
No rewinding. 

**Screenshots**
*Video attached*

https://github.com/Sandakan/Nora/assets/73738591/608db78a-de83-4f3c-8fcc-0d4763c3cf79

**Log File**
Nothing related, just window resizing logs.

**System Information:**

- OS: Windows 10 
- 2.3.0-stable

**Comment by Sandakan** [comment]
@RichardKanshen, Did you modify song metadata while playing that song?

**Comment by RichardKanshen** [comment]
Nope, it just randomly happens for no reason sometimes. It does get fixed after restart, but it is annoying. Maybe it is a glitch in the file system? Electron? Loading files temporarily into memory?

**Comment by Sandakan** [comment]
@RichardKanshen, 
Are those lyrics automatically downloaded during the playback?
Did you enable the option to save downloading lyrics automatically?

**Comment by RichardKanshen** [comment]
> Are those lyrics automatically downloaded during the playback? 
Nope, I downloaded these before and saved them into the tags.

**Comment by Sandakan** [comment]
Saw some signs like you are describing in the app and added a fix for the next update.
Hope that it fixes this problem too.
