### ISSUE TITLE
Bug in Nora - More songs mentioned when there are not.

### ISSUE THREAD

**Issue by RichardKanshen** [Sandakan/Nora#193]
**Describe the bug**
The album panel in Artist, Albums and the View Album screens show incorrect song numbers.

**To Reproduce**

Not sure, but:
1. List both a directory, and its parent directory in the parent folder
2. Nora creates "ghost songs" (which is another issue in and of itself) - They do not have artworks, cannot be played, and amplify Songs In Album numbers.
3. Remove one of the added directories, so the songs can still be listed.
4. "Ghost songs" should disappear on restart, but the numbers will still be incorrect.

**Expected behavior**
Showing the number of songs in the album that are currently available in Nora. 

**Screenshots**
Album Tile:
![image](https://github.com/Sandakan/Nora/assets/73738591/5f48d25d-a9b4-4226-afa2-21bc2e3f6796)
Same Album's Page:
![image](https://github.com/Sandakan/Nora/assets/73738591/7476ed26-caa5-443b-b232-4280f50397e3)

**Log File**
No errors are available - seems like a Library / Filesystem Issue,

**System Information:**

- OS: Windows 10
- Affected App Version: 2.3.0-stable (and 2.2.0-stable as well)

**Comment by RichardKanshen** [comment]
I sadly cannot replicate the bug, but what I mean by that is, Nora shows tracks that are not really supposed to be there? Like, the same song showing up twice in the listing, but one is unplayable and has the default Nora track sleeve.

**Comment by Sandakan** [comment]
Then I'll keep this issue for now.
Made some adjustments to Nora to fix issues like this.
If you still see this error in the new update, mention it to me.

**Comment by RichardKanshen** [comment]
Alright, I will close this as can't repro for now.
