### ISSUE TITLE
Feature Request for Nora - Actual song numbers in the Album View

### ISSUE THREAD

**Issue by RichardKanshen** [Sandakan/Nora#194]
**Is your feature request related to a problem? Please describe.**
It is not exactly an Issue, but Nora lists track numbers in the Album view based the order each song is listed instead of the number in the File Metadata.

**Describe the solution you'd like**
The track numbers could be listed based on what track number is in the metadata, like this:
![image](https://github.com/Sandakan/Nora/assets/73738591/12b064de-5dd9-4164-986e-bd25315d5de6)

**Describe alternatives you've considered**
Maybe there could also be track elements for missing songs, either going until the last song available, or the track total file metadata. Something like this, perhaps:
![image](https://github.com/Sandakan/Nora/assets/73738591/6ebd27c9-8588-42ad-9317-25fa0563f84d)

**Additional context**
For context, this is how Oto Music does it.
![Screenshot_20230906-172222](https://github.com/Sandakan/Nora/assets/73738591/1a0482b7-5fe4-412f-a28d-405b5031f5be)

**Comment by Sandakan** [comment]
what if the track number metadata tag is empty?

**Comment by RichardKanshen** [comment]
If the track number tag is empty, then the resort could be just by alphabetical order, with a "-" for track number, similar how Oto Music shows without a track number.

**Comment by RichardKanshen** [comment]
Just updated and this looks absolutely epic! Thanks a lot!
![image](https://github.com/Sandakan/Nora/assets/73738591/5eb72a41-f09b-4c46-993d-e7cac3479cbc)
