### ISSUE TITLE
Feature Request for Nora - Indexing by file name

### ISSUE THREAD

**Issue by MikeeSierrah** [Sandakan/Nora#196]
Hi, Nora is awesome and great took a while for me to finally settle on on a good desktop music player

but the only problem with Nora that I have is that it doesn't have the feature to index songs by filename 
like I make playlists by sending Musics to the folder and naming them individually on the file 
but Nora reads only the metadata and doesn't read the file name or doesn't allow indexing by filename 

![image](https://github.com/Sandakan/Nora/assets/144580664/ef2de745-26dd-48d2-abde-44798744fd16)

this is what is looks like in my folder. 
but Nora doesn't read it and indexes the music by its metadata name.

i hope you add the feature to index a folder in Nora by file name. 

thanks for making such a great app.

**Comment by Sandakan** [comment]
If there's no title in the song metadata, Nora should take the filename as the title, allowing you to sort by using `A to Z` and `Z to A` options.

**Comment by MikeeSierrah** [comment]
I know but my songs have a metadata song title its annoying to change the metadata title to numbers and it causes some issues.
I just want Nora to be able to index by file name too, it would be convenient.
is it possible?
