### ISSUE TITLE
Feature Request for Nora: Smart Playlists

### ISSUE THREAD

**Issue by princessGasmask** [Sandakan/Nora#201]
Since Nora is already able to come up with "similar songs" in the song info tab, I was wondering if it would be possible to implement a "Smart Playlist" feature where you can queue up similar songs into an automatic playlist?

**Comment by metronightly** [comment]
this feature already kind of exists. When you play a song, go to song info and there you'll probably a list of similar songs that are in your library and you can add those songs to the current playlist 
![image](https://github.com/Sandakan/Nora/assets/75716685/00ec3b1e-ed5d-47fb-a9b1-4fa489eb97a2)
