### ISSUE TITLE
Bug in Nora - Albums getting stuck

### ISSUE THREAD

**Issue by RichardKanshen** [Sandakan/Nora#202]
**Describe the bug**
Switching between different artist pages does not replace the albums

**To Reproduce**

1. Open the artist page of any artist, which allows to navigate directly into a different artist page.
2. Open a different artist page directly from there.

**Expected behavior**
Every artist page should display the correct albums for each artist.

**Screenshots**

https://github.com/Sandakan/Nora/assets/73738591/61792481-f35a-4e6e-8e29-c8cbd826bbd1

**Log File**
N/A

**System Information:**

- OS: Windows 10
- Affected App Version: v2.4.2-stable

**Comment by Sandakan** [comment]
@RichardKanshen Found a fix for this.
It will be fixed in the next update.
