### ISSUE TITLE
Bug in Nora

### ISSUE THREAD

**Issue by navlb** [Sandakan/Nora#203]
Missing so much songs when add folder

**Comment by Sandakan** [comment]
Can you describe your problem more clearly?
If you happen to see less songs in Nora's library, check whether Nora supports song extensions in your library.
Currently Nora only supports,
- mp3
- flac
- m4r
- aac
- wav
- ogg

**Comment by navlb** [comment]
Sorry, my English is not good so the explanation is not clear. I created a new report when I discovered that the app only interacts with .mp3 files (not .MP3). Many files on my device are in .MP3 format and it still works fine with all other media applications
