### ISSUE TITLE
.mp3 and .MP3 case

### ISSUE THREAD

**Issue by navlb** [Sandakan/Nora#204]
Missing so much songs when add folder. App only read .mp3 file and say don't support .MP3 while .MP3 file work well with other app
![Screenshot (14)](https://github.com/Sandakan/Nora/assets/43053371/01d24b2b-2bcf-4f40-a4d4-f88771ea862f)

**Comment by Sandakan** [comment]
Oh, i see, i think that's a fault in my end.
 I'll send a fix for it in the next update

**Comment by Sandakan** [comment]
May i know the reason your songs have a .MP3 extension instead of .mp3
I searched the web to see if allowing apps to run files with case insensitive extensions is a security vulnerability and it stated that it is a possibility.

**Comment by navlb** [comment]
Oh, I see. 2/9 of my list is .MP3, I also see many uppercase extension including these file I download from internet. Today Windows  is case insensitive but some OS and hard drive format recognize 2 file with same name but case sensitive are not the same file. I don't know if uppercase extension file is support and valid in other contexts
