### ISSUE TITLE
Feature Request for Nora - Option/checkbox to disable lock screen media controls

### ISSUE THREAD

**Issue by Anthonyy232** [Sandakan/Nora#205]
**Is your feature request related to a problem? Please describe.**
It would be nice if there is an option to disable the media controls popup that shows up on the lock screen.

**Describe the solution you'd like**
Same as above^^

**Describe alternatives you've considered**
Not sure

**Additional context**

**Comment by Sandakan** [comment]
I don't think that i can disable media controls only on lock screen.
Maybe i can add an option to toggle media controls.

**Comment by Anthonyy232** [comment]
> I think it doesn't work like that. I think Windows will automatically provide media controls when a song playing application is played.

It seems like some Chromium stuff can disable it.
https://www.elevenforum.com/t/enable-or-disable-media-controls-in-windows-11.11505/

**Comment by Sandakan** [comment]
I tried [this](https://stackoverflow.com/a/60022070) workaround but it still shows a play/pause button in lock screen.
