### ISSUE TITLE
Sorting by Disc

### ISSUE THREAD

**Issue by Campirano27** [Sandakan/Nora#211]
In an album with two or more discs, tracks are displayes like "1, 1, 2, 2" instead of sorting them like "Disc 1, Disc 2"

I would like an option so different disks in the same album can be separated

![image](https://github.com/Sandakan/Nora/assets/148821510/9813f7fc-86e3-4d11-9238-88e758b18de7)

This is an example of how it is displayed

I'm sorry if this is already a feature, but I haven't seen an option that allows me to do that

**Comment by RichardKanshen** [comment]
This is an absolute need of a feature, would be great.
