### ISSUE TITLE
Support for local LRC lyrics

### ISSUE THREAD

**Issue by Dsibe** [Sandakan/Nora#215]
**Is your feature request related to a problem? Please describe.**
At the moment, it seems like Nora does not support local LRC lyric files—only those that are stored as ID3 tags. LRC files are a very popular solution to storing lyrics for songs, and it would be truly useful for Nora to support it, especially as it is quite common to have music libraries with downloaded LRCs right next to the songs. 

**Describe the solution you'd like**
Support LRC lyric files: automatically try to load the LRC file (from the song's path, try to load "{SONG_FILENAME}.LRC"). If the file does not exist, fallback to other methods. 

**Additional context**
I have tried placing LRCs next to the songs in my library, and Nora was not able to find them, and because of this, it made me think that this behavior is not currently supported. Please let me know if I should attach any log files, or anything else that could help. 

By the way, thank you very much for making Nora! I tried numerous players for Windows, and Nora is clearly the most beautiful, convenient, and powerful audio player I have ever used. Thank you so much for creating it!

**Comment by Sandakan** [comment]
@Dsibe,
 
Thanks for the compliment 🥰.

Did you mean LRC files?

I already added that feature in my internal builds. You'll be able to play with it in the next update.

**Comment by Dsibe** [comment]
> @Dsibe,
> 
> Thanks for the compliment 🥰.
> 
> Did you mean LRC files?
> 
> I already added that feature in my internal builds. You'll be able to play with it in the next update.

Thank you for such a quick response! Haha, yes, I did mean LRC files. That's great to hear that you've already added that feature. Looking forward to trying it out in the next update!

**Comment by rg991** [comment]
I have LRC files stored in the same folder as the songs, but Nora doesn't show them. My all songs are in FLAC (if it's related to the problem)

**Comment by PrimeTwister** [comment]
> I have LRC files stored in the same folder as the songs, but Nora doesn't show them. My all songs are in FLAC (if it's related to the problem)

having the same problem here
