### ISSUE TITLE
Feature Request for Nora: Support for adding a loop function to enable the repetition of a single line lyric. 

### ISSUE THREAD

**Issue by laraws** [Sandakan/Nora#216]
Currently, I am studying English listening. To further reinforce my understanding, I would greatly appreciate if you could incorporate a single lyric line loop function into the program, allowing the repeated playback of the spoken content. Thank you in advance for your additional support.

**Comment by Sandakan** [comment]
@laraws, 
I have decided to add a similar feature to Nora, which allows you to go back to the previous synced lyrics line by pressing `Alt` + `Up Arrow` buttons.
It will be released in the next update.
