### ISSUE TITLE
Mac compatibility

### ISSUE THREAD

**Issue by AISLVE** [Sandakan/Nora#217]
Can we expect a mac version, i can build myself if it has the option atleast

**Comment by Sandakan** [comment]
@AISLVE,
Currently, I don't have any plans to release Nora on Mac OS.
You are welcome to build it yourself, but you may notice restrictions in some online services because of not including the relevant API keys.

**Comment by AISLVE** [comment]
no problem man, it's very beautiful, hats off sir
