### ISSUE TITLE
Bug in Nora: Lyric content display doesn't update after updating the lyric content at the song

### ISSUE THREAD

**Issue by steamplaywith** [Sandakan/Nora#218]
The app does not update the displayed lyrics to reflect the latest content changes made and saved using other mp3 editors. Is there a cache involved and if so, how can it be cleared?

**Comment by Sandakan** [comment]
@steamplaywith,
It should clear the lyrics cache.
Can you confirm that lyrics got properly saved by the other media player?

**Comment by steamplaywith** [comment]
> @steamplaywith, It should clear the lyrics cache. Can you confirm that lyrics got properly saved by the other media player?

I can confirm that I have successfully saved the new changes of the lyric content to the mp3 file. It is functional on other apps, but not on this one.

Is there another way to clear the lyrics cache, such as manually deleting the cache file?

**Comment by steamplaywith** [comment]
> @steamplaywith, It should clear the lyrics cache. Can you confirm that lyrics got properly saved by the other media player?

Even after deleting the entire `$HOME/.config/Nora` folder, the problem still persists.

**Comment by Sandakan** [comment]
> @steamplaywith, It should clear the lyrics cache. Can you confirm that lyrics got properly saved by the other media player?
> I can confirm that I have successfully saved the new changes of the lyric content to the mp3 file. It is functional on other apps, but not on this one.
> Is there another way to clear the lyrics cache, such as manually deleting the cache file?

Can you send me that song to further check on this problem?
