### ISSUE TITLE
Add new languages to Nora

### ISSUE THREAD

**Issue by senolfndk** [Sandakan/Nora#219]
Can you add Turkish language?

**Comment by Sandakan** [comment]
### To add new languages, you have to translate the entries of the [en.json](https://github.com/Sandakan/Nora/blob/master/assets/locales/en/en.json) file into a new file.

**Comment by senolfndk** [comment]
I'm not an expert on this subject

**Comment by Sandakan** [comment]
> I'm not an expert on this subject

It's okay. I also don't have the knowledge to translate into different languages, so we may have to wait until someone translates the document to that language.

**Comment by senolfndk** [comment]
> > Bu konunun uzmanı değilim
> 
> Sorun değil. Ayrıca farklı dillere çeviri yapacak bilgim de yok, bu nedenle birisinin belgeyi o dile çevirmesini beklememiz gerekebilir.

ok
