### ISSUE TITLE
Add support for .opus files

### ISSUE THREAD

**Issue by WILLIANWILLOFC** [Sandakan/Nora#220]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex: I'm always frustrated when...

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sandakan** [comment]
@WILLIANWILLOFC ,
I'm sorry to say this but Nora won't be able to support the OPUS files because the chromium engine that is used to run Nora doesn't include the relevant codecs to decode those files.
