### ISSUE TITLE
Please add a full screen player , i have multi monitors it would look good if there is album art on one monitor in full screen

### ISSUE THREAD

**Issue by SK-I-3256** [Sandakan/Nora#222]
**Is your feature request related to a problem? Please describe.**
NO , it is not a problem just a request

**Describe the solution you'd like**
I have 4 monitors and i would love it if you would add a full screen player as it will look good on one monitor

**Describe alternatives you've considered**
I have 4 monitors and i would love it if you would add a full screen player as it will look good on one monitor
**Additional context**
I have included a screenshot (Something like this , This is from Dopamine Music Player)

![image](https://github.com/Sandakan/Nora/assets/144821335/624cc876-97f6-4cdb-b358-bbc9d54b613e)

**Comment by Sandakan** [comment]
@SK-I-3256, 
I'll see what i can do.
