### ISSUE TITLE
Bug in Nora- It cannot scan a folder with 1500 songs , it just shows 25 songs

### ISSUE THREAD

**Issue by SK-I-3256** [Sandakan/Nora#223]
**Describe the bug**
Cannot scan a folder with 1500 songs , it just shows 25 songs

**To Reproduce**

1. Go to folder and add you folder with songs
2. Click on add folder
3. Go to songs
4. Not all songs are there , out of 1500 songs there are only 25 songs

**Expected behavior**
Cannot scan a folder with 1500 songs , it just shows 25 songs

**Screenshots**

https://github.com/Sandakan/Nora/assets/144821335/01882371-5dfa-4986-8830-ef7136a93cf5

**Log File**
Please attach the log file of the app to better understand what went wrong in the app.
It is situated in C:\Users\USER_NAME\AppData\Roaming\nora\logs.txt
[2023-12-23.prod.log.txt](https://github.com/Sandakan/Nora/files/13759503/2023-12-23.prod.log.txt)

**System Information:**

- OS: Windows 11 22H2
- Affected App Version: 2.5.0

**Additional context**

**Comment by Sandakan** [comment]
@SK-I-3256, 
I have more than 1800 songs in my Music folder, and Nora detects it correctly.
Check whether all the songs in your Music folder are supported by Nora. 
If Nora doesn't support them, they won't be added to the library.

**Comment by SK-I-3256** [comment]
> @SK-I-3256, I have more than 1800 songs in my Music folder, and Nora detects it correctly. Check whether all the songs in your Music folder are supported by Nora. If Nora doesn't support them, they won't be added to the library.

ALL the files are mp3 320kbps 44.1khz , no m4a or flac , I have crossed checked , I tried to uninstall and reinstall the app , I gave the video, have you seen ,  can you provide some suggestion to fix this issue, Please

**Comment by Sandakan** [comment]
@SK-I-3256, 
Can you check whether the song extension is in uppercase or lowercase?
Currently, Nora only recognizes songs with extensions that are in lowercase `mp3`.  Uppercase `MP3` is not supported for additional security.

If the extensions are also in lowercase, can you provide me with few songs that didn't parse so that i can find the problem.

**Comment by SK-I-3256** [comment]
> @SK-I-3256, Can you check whether the song extension is in uppercase or lowercase? Currently, Nora only recognizes songs with extensions that are in lowercase `mp3`. Uppercase `MP3` is not supported for additional security.
> 
> If the extensions are also in lowercase, can you provide me with few songs that didn't parse so that i can find the problem.

Thank you so much , i used bulk file renamer and changed the extension to lowercase , now it works properly thank you.
Love the Player❤️❤️
