### ISSUE TITLE
No m4a support?

### ISSUE THREAD

**Issue by the-root-user** [Sandakan/Nora#224]
**Bug / Feature Request**
From my music folder with mp3s and m4as, none of the m4a shows in Nora, though, they do in Otto ;)

I don't know if it is a bug or a feature request OR whether it will be worked on.. let us know. 

**Additional context**
Been using Nora for a while.

**Comment by Sandakan** [comment]
I'm sorry to mention that Nora doesn't support the `m4a` extension.
Unless the chromium project decides to include the correct codec to decode `m4a` files with the chromium build, Nora won't support that extension.

**Comment by the-root-user** [comment]
Ah.. didn't have idea chromium stuff going on.
As they work in Otto, I thought it might be as much as to just tweak the file scan or something like that :D
