### ISSUE TITLE
Bug in Nora: Custom tags breaking playback

### ISSUE THREAD

**Issue by popcornkerne1** [Sandakan/Nora#231]
**Describe the Bug**
Songs that have previously had tags edited on a different device will not play on Nora

**To Reproduce:**
1. Edit a .flac file in Oto Music, change album art, artist name, song name, whatever, just change anything
2. import song into Nora
3. attempt to play the song
4. the result is an error screen saying the song is corrupted

**Expected behaviour:**
for the song to play as normal without an error

**Screenshots**
![Screenshot from 2024-02-10 20-59-33](https://github.com/Sandakan/Nora/assets/92425935/18a51ddd-d73c-46bf-a39c-9d5b374f8dcd)

**Log File**
https://pastebin.com/raw/HFFURhvd
(this is the chunk from startup to the error message)

**System Information**
- OS: Fedora Linux 39
- Affected app version: 2.5.0-stable>

**Additional Context:**
All audio files apart from those edited manually play completely fine
All the "corrupted" files have been sorted into a single genre by Nora, labelled simply as "Genre"

**Comment by Sandakan** [comment]
@popcornkerne1, 
Can you send me a song that doesn't work on Nora? I'll check it out.
This is probably an error in the Chromium.

**Comment by onthejobtraining** [comment]
Similar to issue #190 and #184. I fixed those files by manually editing every single one of them on mp3tag, hope it's fixed asap🙂
