### ISSUE TITLE
No features / multiple artists shown in .flac files

### ISSUE THREAD

**Issue by dimostheenis** [Sandakan/Nora#232]
**Describe the bug**
There are no other artists shown in nora except the main artist when the file is .flac
**EDIT: THIS ALSO HAPPENS ON .MP3 FILES FOR SOME REASON**

**To Reproduce**
1. Add .flac song to Nora
2. Add multiple artists from properties

**Expected behavior**
Multiple artists shown

**Screenshots**
![Nora_P1u2301vqV](https://github.com/Sandakan/Nora/assets/76966291/4553862c-47c5-4cd2-972c-686e9a2f106f)
![explorer_SnNC8jiuHy](https://github.com/Sandakan/Nora/assets/76966291/b055008f-6ac6-4a37-b2f7-1fa0268bcf41)

**System Information:**

- Windows 11 Home 23H2
- v2.5.0-stable

**Additional context**
There is also another issue with .flac files that Resyncing Library does not detect them

**Comment by onthejobtraining** [comment]
Until these issues are fixed - one trick is to load all your files into mp3tag and then ctrl+a followed by ctrl+s to save those tags. I've faced the additional issue too, the trick for that one is mass saving of file name instead. They may not work all the time though

**Comment by dimostheenis** [comment]
No the issue is still here

**Comment by onthejobtraining** [comment]
> No the issue is still here

follow the previous steps I mentioned above, use mp3tag application to properly tag all your files.

**Comment by dimostheenis** [comment]
> > No the issue is still here
> 
> follow the previous steps I mentioned above, use mp3tag application to properly tag all your files.

I was always using mp3tag in the first place, the issue is still there

**Comment by onthejobtraining** [comment]
> > > No the issue is still here
> > 
> > 
> > follow the previous steps I mentioned above, use mp3tag application to properly tag all your files.
> 
> I was always using mp3tag in the first place, the issue is still there

select all your files on mp3tag and use this to change the file names: 
![image](https://github.com/Sandakan/Nora/assets/75716685/39b76f9a-cf32-4d34-a437-4c671f3e9a31)

Just select any format for file renaming and then apply the changes.
