### ISSUE TITLE
Album Artist Instead of Artists for Last.fm Scrobbling

### ISSUE THREAD

**Issue by GhoulBoii** [Sandakan/Nora#235]
**Is your feature request related to a problem? Please describe.**
Most songs on last.fm are scrobbled by their album artist rather than the artists. Scrobbling through artists is fine unless multiple artists are collaborating on one song which leads to inconsistency with the scrobble names. 

**Describe the solution you'd like**
Use album artist instead of artists to scrobble to last.fm and the better solution would be to add a toggle to switch between scrobbling album artist or artists.

**Describe alternatives you've considered**
I could possibly install a desktop scrobbler but I would rather use the native scrobbler in nora and make it function better.

**Additional context**
Scrobbling Lyrical Lemonade, Cordae, Juice Wrld - Doomsday
With nora: https://www.last.fm/music/Lyrical+Lemonade,+Juice+WRLD,+Cordae/_/Doomsday+(with+Juice+WRLD+&+Cordae)
With spotify: https://www.last.fm/music/Lyrical+Lemonade/_/Doomsday+(with+Juice+WRLD+&+Cordae)

**Comment by Sandakan** [comment]
Thanks for the suggestion, I'll see what I can do.

**Comment by Sandakan** [comment]
@GhoulBoii 
I already send the album artist along with the song artists when scrobbling a song

**Comment by GhoulBoii** [comment]
> @GhoulBoii I already send the album artist along with the song artists when scrobbling a song

I am suggesting to scrobble the album artist in the artists field. As per my testing, setting the album artist does not have any impact on the track that is scrobbled other than the album art. Setting it as the artists would fix the issue and avoid duplicate tags.

**Comment by Sandakan** [comment]
> > @GhoulBoii I already send the album artist along with the song artists when scrobbling a song
> 
> I am suggesting to scrobble the album artist in the artists field. As per my testing, setting the album artist does not have any impact on the track that is scrobbled other than the album art. Setting it as the artists would fix the issue and avoid duplicate tags.

I'll give it a try and get back to you
