### ISSUE TITLE
Wrong album number for artists

### ISSUE THREAD

**Issue by sk-pathak** [Sandakan/Nora#238]
**Describe the bug**
The number of albums for all artists in the artists page shows 0.

**Screenshots**
![Screenshot (274)](https://github.com/Sandakan/Nora/assets/114680963/2b1d45d0-f750-41f8-8cb6-99d3646069a1)

**System Information:**

- Windows 11
- v2.5.0-stable

**Comment by Sandakan** [comment]
@sk-pathak Can you verify whether each album on those songs has the album artist as `IU`?

**Comment by sk-pathak** [comment]
Yes, also this is happening for every artist not just one

![Screenshot (275)](https://github.com/Sandakan/Nora/assets/114680963/462439f0-014a-4a41-8ffb-db5763a17ed6)

**Comment by Sandakan** [comment]
I'll look into it.
