### ISSUE TITLE
OPUS Support (Feature Request for Nora)

### ISSUE THREAD

**Issue by HelveticAlex** [Sandakan/Nora#242]
**Is your feature request related to a problem? Please describe.**
As .OPUS is becoming increasingly relevant and serves as a direct replacement for .MP3, its absence limits the usability of the platform for users who prefer or require .OPUS for its superior efficiency and quality.

**Describe the solution you'd like**
I would like Nora to implement support for the [.OPUS audio codec.](https://en.wikipedia.org/wiki/Opus_(audio_format)).

**Describe alternatives you've considered**
An alternative solution could be continuing to convert .OPUS files to other supported formats like .MP3 or .AAC, but this results in a loss of quality and/or increased file sizes, which is not ideal. Native .OPUS support would be a much more efficient and quality-preserving option.

**Additional context**
Adding .OPUS support could also align Nora with modern audio standards and practices, as more devices and platforms are beginning to adopt .OPUS due to its advantages over other audio formats. This enhancement would not only improve functionality but also future-proof the platform as media standards evolve.

**Comment by Sandakan** [comment]
@HelveticAlex, 
I have tried to enable support for other codecs on Nora.

But the main problem is that chromium only comes with a handful of audio codecs to work with and I have no idea how to integrate more codecs to it.

**Comment by Sandakan** [comment]
@HelveticAlex,
It does work. But it won't support metadata editing because the package I'm using only supports mp3.

**Comment by Sandakan** [comment]
> Mhmm, what about https://www.npmjs.com/package/music-metadata-browser ?
> 
> It requires a little more work, but given the number of metadata supported, it could be incredible for Nora !

I'm already using its nodejs implementation and it only supports reading metadata.
