### ISSUE TITLE
Feature Request - Fullscreen Player - Remember Lyrics Off/On

### ISSUE THREAD

**Issue by Neptune-mk2** [Sandakan/Nora#248]
Currently in version 3.0.0 stable Nora does not remember if you turn off the lyrics display in the new fullscreen music player mode.

This results in the lyric display always being enabled every time you close it and open it, change album, or open a playlist, and also means any song that doesn't have lyrics displays the "Lyrics not found" watermark which can be annoying since some songs do not always have lyrics.

Proposed fix is to have it remember the state of the lyrics display being on/off.

Though I think in general the "no lyrics" watermark should just be replaced with something less obtrusive, perhaps remove the text and move the " ! " symbol into the lyrics button similar to how a app badge notification is displayed, when the user hovers over it have it caption "No lyrics found".

```
Additional information
-
Nora - 3.0.0-Stable
OS - Windows 11 Version 23H2 (OS Build 22631.3593)
```

**Comment by Sandakan** [comment]
@Neptune-mk2 
Thanks for the recommendations.
I'll see what I can do.
