### ISSUE TITLE
UI Shows double file names for some songs

### ISSUE THREAD

**Issue by antonioxsimic** [Sandakan/Nora#250]
Basically some songs show double file name, while in spotify for example, this doesnt happen with that same MP3
![Screenshot_4](https://github.com/Sandakan/Nora/assets/154445646/d1cf1fde-ffc6-4ce6-a35b-6a0a641fec01)

**Comment by antonioxsimic** [comment]
![Screenshot_5](https://github.com/Sandakan/Nora/assets/154445646/ac2624ef-79f1-469d-988e-ccadccf538c3)
Just noticed its the same with Album names

**Comment by Sandakan** [comment]
@antonioxsimic Can you send me a sample song?

**Comment by antonioxsimic** [comment]
![Screenshot_7](https://github.com/Sandakan/Nora/assets/154445646/6b89faed-8e88-444e-a7f7-acefcf728a17)
I uploaded it here in drive
https://drive.google.com/file/d/1rN4-Wa1VFcuE6lIJxabjrd2oNTGgICPF/view?usp=sharing

**Comment by Sandakan** [comment]
@antonioxsimic 
![image](https://github.com/Sandakan/Nora/assets/45460443/34e813b7-ff1e-426d-84c7-fbc7fd1d56ae)

Nora is showing the correct metadata from your song.
It has only stripped `\\` characters from metadata.

**Comment by antonioxsimic** [comment]
What do you think why isn't the same thing visible in Foobar or other metadata editors? I have never typed "Pjevacica", i typed "Pjevačica", with european characters
