### ISSUE TITLE
Feature: Lyrics lines can be copied.

### ISSUE THREAD

**Issue by laraws** [Sandakan/Nora#253]
When the lyrics are in foreign languages, I want to copy the lyrics by hovering my mouse over the lyrics line and then using Ctrl + C to copy it for translating using Google Translate. I hope you can provide this function, as it is really helpful for me. Thank you.

**Comment by onthejobtraining** [comment]
There's already a translate button btw. 
![image](https://github.com/Sandakan/Nora/assets/75716685/2c57b91a-96c7-4984-bace-b6a4a9d92e63)

**Comment by laraws** [comment]
> There's already a translate button btw. ![image](https://private-user-images.githubusercontent.com/75716685/334141832-2c57b91a-96c7-4984-bace-b6a4a9d92e63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjE2NjYsIm5iZiI6MTcxNjgyMTM2NiwicGF0aCI6Ii83NTcxNjY4NS8zMzQxNDE4MzItMmM1N2I5MWEtOTZjNy00OTg0LWJhY2UtYjZhNGE5ZDkyZTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE0NDkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNWMwYjI4YzI0NzQxY2FhZDQzMWI2YTA5YzVhY2VhODAxOTFmMzQ0NDQ0NGY2NWYxMjVmYWQ3NTRjMzBmMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HV_QRbzqMpgb4iyrwmdnVqEarohLX4pczUoOLRkVaa0)

Thank you for your reply. It's helpful. However, I would prefer to have the copy feature as it is more flexible.

**Comment by onthejobtraining** [comment]
> > There's already a translate button btw. ![image](https://private-user-images.githubusercontent.com/75716685/334141832-2c57b91a-96c7-4984-bace-b6a4a9d92e63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjE2NjYsIm5iZiI6MTcxNjgyMTM2NiwicGF0aCI6Ii83NTcxNjY4NS8zMzQxNDE4MzItMmM1N2I5MWEtOTZjNy00OTg0LWJhY2UtYjZhNGE5ZDkyZTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE0NDkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNWMwYjI4YzI0NzQxY2FhZDQzMWI2YTA5YzVhY2VhODAxOTFmMzQ0NDQ0NGY2NWYxMjVmYWQ3NTRjMzBmMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HV_QRbzqMpgb4iyrwmdnVqEarohLX4pczUoOLRkVaa0)
> 
> Thank you for your reply. It's helpful. However, I would prefer to have the copy feature as it is more flexible.

agreed

**Comment by Sandakan** [comment]
@laraws, You can copy lyrics by right-clicking the song and going to the song tags editor lyrics section.

**Comment by laraws** [comment]
> @laraws, You can copy lyrics by right-clicking the song and going to the song tags editor lyrics section.

Thank you for your tip. But I think it can be more convenient if I can just copy a line of lyric when playing a music.
