### ISSUE TITLE
Feature: Customize the lyric color and the UI font size of the app.

### ISSUE THREAD

**Issue by laraws** [Sandakan/Nora#255]
After trying version 3.0.0, I found that the lyric color was different from version 2.5.0. I was used to the color of 2.5.0, so I hope the app can support customizing the lyric color. Additionally, I noticed that the font size of the UI in 3.0.0 is much smaller compared to 2.5.0. I hope it can support customizing the font in the UI as well. Thx.

My system is ubuntu 22.04.

**Comment by Salah242222** [comment]
+1 or only allow changing the font color when dynamic theme is disabled
