### ISSUE TITLE
Album Covers not showing in file explorer

### ISSUE THREAD

**Issue by Rueby** [Sandakan/Nora#257]
This feels like a really particular nitpick, but I think the metadata search on Nora is far less scuffed than mp3tag, however I'd also like the album cover for songs to appear in the file explorer.

I think there's some kind of conflict with the formats? I go around it by adjusting the metadata, saving the artwork as .jpeg then going with mp3tag and replacing the cover. I'm wondering if this is within the scope of the app or is this something beyond it? Thanks alot!

I'm using windows 10 for reference, I'm not sure if windows 10's file explorer is less scuffed when it comes to showing thumbnails.

**Comment by Sandakan** [comment]
@Rueby, 
Whenever Nora edits song metadata, it will always try to save the artwork in `.png` format and it works for me in both Windows 10/11 File Explorers.
