### ISSUE TITLE
Publish on Flatpak

### ISSUE THREAD

**Issue by IkelAtomig** [Sandakan/Nora#262]
Flatpak is getting well recognized. If app is available, it would cut down releases to AppImage (Of course for portability), Snap (Cuz Ubuntu doesn't have Flaptak by default, AFAIK)

Flatpak used by most people and it be would easier too to manage than `.deb` and `.rpm`

**Comment by IkelAtomig** [comment]
There is a relevant pull request, so bot open.


Aug 15, 2024, by ***@***.***:

**Comment by DodoLeDev** [comment]
Hi! If possible, I would like to reopen this issue, because I'm starting to work on a Flatpak port

**Comment by Sandakan** [comment]
Sorry to keep you waiting.
Currently, I'm rewriting the app with some major improvements, and it will take some time to complete, given the limited time I have.
I wanted to address some major issues with the app, so I decided to release a major version update incorporating these changes.
I'll check out and merge the pull request once I complete some important parts of the app.

**Comment by 12people** [comment]
Ah, ok.
Thanks for the quick answer!
