### ISSUE TITLE
Cheatsheet for Keyboard Shortcuts

### ISSUE THREAD

**Issue by srshah27** [Sandakan/Nora#264]
A cheatsheet with all the keyboard shortcuts would be great to navigate around. I was specifically looking to seek song by +/- 10 or 5 sec. Arrow keys did not seem to do that. Rest all shortcuts were easy to find.

**Comment by Sandakan** [comment]
@srshah27,
There is a list of shortcuts if you go to the bottom of the settings page, where there is a button named `App Shortcuts` to prompt the available shortcuts.
