### ISSUE TITLE
Nora won't automatically recognize new files

### ISSUE THREAD

**Issue by Optinux** [Sandakan/Nora#271]
I sync my music files using [Syncthing](https://github.com/syncthing/syncthing). Sadly Nora won't automatically recognize new files synced by Syncthing and they thus don't show up in recent files. 

This is very likely not caused by Syncthing. There isn't any kind of special way Syncthing places files in the directory. 
Weirdly, the files do get recognized by Nora if I force a rescan of all folders (eg. by removing and re-adding my music folder). Its just that they don't get recognized automatically. Moreover, files only show up automatically without having to rescan when placing them in the folder by hand.

Possible Fix: add a rescan button, that manually checks for new files

**Comment by Sandakan** [comment]
Can you provide the log files which are located in the `C:\Users\USER_NAME\AppData\Roaming\nora\logs` directory
