### ISSUE TITLE
Can't connect to Last.fm

### ISSUE THREAD

**Issue by kirbloz** [Sandakan/Nora#273]
![immagine](https://github.com/user-attachments/assets/00f19370-e275-410a-9e8a-0d2bc1ac8fb4)
as the title says.. whenever i click on the "Login via Web" button, this is what i see. 
i am using the latest version of arch linux and the web browser is firefox.

**Comment by onthejobtraining** [comment]
Have you created an api key on last.fm first?

**Comment by onthejobtraining** [comment]
https://www.last.fm/api/authentication

**Comment by kirbloz** [comment]
@onthejobtraining i absolutely did not, thank you! for some reason i assumed it was all handled software wise.

**Comment by onthejobtraining** [comment]
> not sure what i should put in the callback url field

Sorry for the late response. Just enter application name as 'Nora' or 'Test' and then submit, you don't need to fill the other stuff. After that, visit this page: https://www.last.fm/api/accounts and copy the api key from here.

**Comment by kirbloz** [comment]
dont't worry!
> visit this page: https://www.last.fm/api/accounts and copy the api key from here.
i can do that np, but i have no idea where to put the api key. i tried peeking around in the source code but can't quite figure it out.

**Comment by onthejobtraining** [comment]
but even if i click accept, its stuck there.

![image](https://github.com/user-attachments/assets/5bf76fb3-e92b-44e9-bdd3-b0f534f3f9d0)
after clicking on 'allow access', you don't have to do anything. Go back to Nora and you'll see a message like this 
![image](https://github.com/user-attachments/assets/4b8cfc56-3f55-4ad7-bdcc-0bc971d054f9)

**Comment by kirbloz** [comment]
tried following the steps from scratch and still nothing.
![immagine](https://github.com/user-attachments/assets/2f3251b1-2435-49a6-b0a5-b8b372381482)
lastfm web page stuck, nora not showing any messages. nothing in the dev tools page or ever the log

**Comment by onthejobtraining** [comment]
Share a screenshot of this page: https://www.last.fm/api/accounts with the api keys and codes blurred or hidden of course.

**Comment by kirbloz** [comment]
unfortunately logging out and clearing browser data did not work.
![immagine](https://github.com/user-attachments/assets/290b7d3f-0874-49ea-b482-f53d3ee09153)
this is the screenshot you requested
i might be thinking of reinstalling nora from scratch but i dont know if that will fix it

**Comment by onthejobtraining** [comment]
You're on the latest version, right? Try posting in the discord server, maybe someone has a solution.

**Comment by Sandakan** [comment]
@kirbloz, do you accept a popup like this when you click `Yes, Allow Access`?
![image](https://github.com/user-attachments/assets/a3934a2c-e81d-4638-9368-25c2bb692752)

**Comment by onthejobtraining** [comment]
@kirbloz
