### ISSUE TITLE
Nora Setup 3.0.0 for Windows won't start

### ISSUE THREAD

**Issue by scythehusband** [Sandakan/Nora#275]
what it says on the tin. no error code or popup or anything*, it just doesn't start. i tried running as administrator, still didn't start. i tried downloading the source code, still doesn't start. fyi i am tech illiterate. please help.

*besides the usual microsoft "unidentified publisher" popup, i was exhausted and frustrated when i initially wrote this and it completely slipped my mind to mention that. i always click "run anyway" and as stated below i have "choose where to get apps" set to "anywhere," but microsoft appears to have taken away all my agency in this matter :')

**Comment by onthejobtraining** [comment]
Follow this steps: https://support.microsoft.com/en-us/windows/change-your-app-recommendation-settings-in-windows-f21b5c60-e996-4ee4-c2cf-b4a90c0bef9b

**Comment by scythehusband** [comment]
> Follow this steps: https://support.microsoft.com/en-us/windows/change-your-app-recommendation-settings-in-windows-f21b5c60-e996-4ee4-c2cf-b4a90c0bef9b

i already have it set to "anywhere"

**Comment by onthejobtraining** [comment]
> i already have it set to "anywhere"

Post a screen recording and screenshot of the process. Because this seems like an issue with your system and device, not the nora setup file.

**Comment by scythehusband** [comment]
> > i already have it set to "anywhere"
> 
> Post a screen recording and screenshot of the process. Because this seems like an issue with your system and device, not the nora setup file.

it was! i added it to my microsoft defender exclusions list and it finally worked properly. can't believe i forgot about checking that until now.

**Comment by onthejobtraining** [comment]
Nice. You can close the issue now.
