### ISSUE TITLE
Automatically Sync Music Folder? 

### ISSUE THREAD

**Issue by jevonsp** [Sandakan/Nora#276]
Description: The "resync library" button in the settings doesnt seem to update my library after adding new music folders. Manually adding the folders through the sidepanel does work. 

Reproduce: Add a new sub folder to the default music folder selected by Nora, the new files wont show up after clicking the "resync library" button in the settings panel

OS: Win 10 10.0.19045 Build 19045

**Comment by onthejobtraining** [comment]
Similar to #271
