### ISSUE TITLE
hi , I have an error in linux 

### ISSUE THREAD

**Issue by dani0221** [Sandakan/Nora#279]
When extracting the appImage file and running , it gives this error, 

[Tue, 17 Sep 2024 20:57:35 GMT] [MAIN] = No default protocol registered. Starting the default protocol registration process. 
	

[Tue, 17 Sep 2024 20:57:35 GMT] [MAIN] = Default protocol registration failed. 
	

[Tue, 17 Sep 2024 20:57:35 GMT] [MAIN] = Checking for update 
	

[Tue, 17 Sep 2024 20:57:35 GMT] [MAIN] = Window state changed 
	{"state":"maximized"}

[Tue, 17 Sep 2024 20:57:35 GMT] [MAIN] = Data update event fired with updated 'userData'. 
	
[1] 28669 segmentation fault (core dumped) ./Nora.Setup.3.0.0-stable-linux-x86_64.AppImage

**Comment by dani0221** [comment]
This happened after installing vips, since before it gave an error of libvips42, PS: it is fedora linux

**Comment by onthejobtraining** [comment]
Did you fix the error?

**Comment by dani0221** [comment]
> Did you fix the error?

No, the error is in version 3.0.0, but in version 2.5.0 it works
