### ISSUE TITLE
Crashing when playing FLAC files.

### ISSUE THREAD

**Issue by thrabi** [Sandakan/Nora#280]
Shows the following error.
CODE 4 : DEMUXER_ERROR_COULD_NOT_OPEN: FFmpegDemuxer: open context failed

**Comment by onthejobtraining** [comment]
To confirm the issue about chromium, if you're on windows you can try to open the flac file with microsoft edge from the context menu and you'll see that edge will also not be able to play that song whereas something like firefox will be able to play it perfectly.

**Comment by thrabi** [comment]
> Yeah, it's a known bug that occurs while playing some flac files because of chromium: #190 #184
> 
> What I usually do to 'fix' this issue is change some tags using mp3tag. And then select all files on mp3tag and use this to change the file names: ![image](https://private-user-images.githubusercontent.com/75716685/331648020-39b76f9a-cf32-4d34-a437-4c671f3e9a31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NjQ3NzIsIm5iZiI6MTcyNjc2NDQ3MiwicGF0aCI6Ii83NTcxNjY4NS8zMzE2NDgwMjAtMzliNzZmOWEtY2YzMi00ZDM0LWE0MzctNGM2NzFmM2U5YTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE2NDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMGZlZjRiZjU0ZWRjOGNlMjZkMzZlODNiMzUwYTJhYjYwODBhOWRhYmI5ODdmODczNTY0MmRmMWY0YTE4NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1RzSsHpQ40fB4T0Mu7Uqh7A7bn_cVu__hmbCAjP1lVE) Just select any format for file renaming and then apply the changes.
> 
> You can also try to do a flac to flac convert using foobar2000 and see if they song plays then ([navidrome/navidrome#2437](https://github.com/navidrome/navidrome/issues/2437))

I found out an easy fix. Select all files in Mp3tag editor and change the album covers to 500x500. Every FLAC files play now.
