### ISSUE TITLE
Lyrics presentation (Requests)

### ISSUE THREAD

**Issue by BluFlames** [Sandakan/Nora#281]
1.  Align the Lyrics to center
2.  Don't display text or content present in square brackets ( [ ] ) of lyrics.  Like [ti : -----] , [ar : ----] , [al : ----] etc.
3. Bold font for Lyrics
4. Please remove the time line below every timestamped lyrics. It's not useful.
![Screenshot 2024-09-21 131012](https://github.com/user-attachments/assets/e9aef118-1fb0-4fdf-ae1c-c7e5b27ea1f1)

**Comment by onthejobtraining** [comment]
Aren't lyrics already aligned to center?

**Comment by Sandakan** [comment]
- Lyrics are already centered except on full-screen.
- Nora already ignores lyrics metadata. Can you provide a sample LRC file?
- The current `Poppins` font looks bad when set to bold. However, I changed the current lyrics line to a medium font-weight to improve visibility.
- The lyric line timeline is a feature I wanted for Nora because I wanted to see the line duration.

**Comment by BluFlames** [comment]
> Aren't lyrics already aligned to center?

I'm sorry I forgot to mention full screen;
I was too excited to use this app for the first time

**Comment by BluFlames** [comment]
> * Lyrics are already centered except on full-screen.
> * Nora already ignores lyrics metadata. Can you provide a sample LRC file?
> * The current `Poppins` font looks bad when set to bold. However, I changed the current lyrics line to a medium font-weight to improve visibility.
> * The lyric line timeline is a feature I wanted for Nora because I wanted to see the line duration.


Full screen is not actually full screen. It felt incomplete, it's ok not a big deal.

[1. Die With A Smile.zip](https://github.com/user-attachments/files/17268973/1.Die.With.A.Smile.zip)
Most of the lyrics that are readily available, that are time synced , do have that metadata kind of thing about the song. Would be nice to see that gone.

Bold in the sense, like on Spotify bold lyrics.

Can you make a toggle to turn off lyric line? Would be helpful

Just a light movement of any key or mouse would bring back the album art in full screen; Make it as the same way in Oto music

Album art blur could be improved; It feels like it's zoomed and not blurred.

Brother, you are doing a great work, putting out useful things for the people, so please keep up the good work.

Really love Nora
