### ISSUE TITLE
Draggable songs in Queue

### ISSUE THREAD

**Issue by Sandakan** [Sandakan/Nora#63]
It would be better if the app allowed to correct the order of the songs in the queue by dragging and dropping them.

The easiest solution is to use an npm package for achieve this functionality.

**Comment by JustCallMeQuincy** [comment]
There's already a base for this, it just needs some cleaning up and it should work properly

**Comment by Sandakan** [comment]
I thought that this functionality is broken, but seems like it's working properly.



> There's already a base for this, it just needs some cleaning up and it should work properly

@JustCallMeQuincy  Did you find something wrong with it?

**Comment by JustCallMeQuincy** [comment]
Works perfectly in 2.0.0-stable!
